### ISSUE TITLE
DD calibration crashes - shape mismatch !?

### ISSUE THREAD

**Issue by amisk** [mhardcastle/ddf-pipeline#105]
Hey. This time I tried a different, quite old dataset.
After three days, it crashed while doing the direction dependent calibration
```

============================== DD calibration =============================

Solutions file /data/amisk/N4631/data/SOLSDIR/L192989_SAP000_SB000_uv_123A9AE4Dt_120MHz.pre-cal.ms/killMS.DDS0.sols.npz already exists, not running killMS step
Solutions file /data/amisk/N4631/data/SOLSDIR/L192989_SAP000_SB000_uv_123A9AE4Dt_130MHz.pre-cal.ms/killMS.DDS0.sols.npz already exists, not running killMS step
Solutions file /data/amisk/N4631/data/SOLSDIR/L192989_SAP000_SB000_uv_123A9AE4Dt_139MHz.pre-cal.ms/killMS.DDS0.sols.npz already exists, not running killMS step
Solutions file /data/amisk/N4631/data/SOLSDIR/L192989_SAP000_SB000_uv_123A9AE4Dt_148MHz.pre-cal.ms/killMS.DDS0.sols.npz already exists, not running killMS step
Solutions file /data/amisk/N4631/data/SOLSDIR/L192989_SAP000_SB000_uv_123A9AE4Dt_158MHz.pre-cal.ms/killMS.DDS0.sols.npz already exists, not running killMS step
Solutions file /data/amisk/N4631/data/SOLSDIR/L192989_SAP000_SB000_uv_123A9AE4Dt_167MHz.pre-cal.ms/killMS.DDS0.sols.npz already exists, not running killMS step
Solutions file /data/amisk/N4631/data/SOLSDIR/L192989_SAP000_SB000_uv_123A9AE4Dt_177MHz.pre-cal.ms/killMS.DDS0.sols.npz already exists, not running killMS step
Running: MergeSols.py --SolsFilesIn=solslist_4873026783.005561.txt --SolFileOut=DDS0_4873026783.005561_merged.npz
 - 09:51:31 - ClassInterpol             | Running Merge on the following SolsFile:
 - 09:51:31 - ClassInterpol             |   /data/amisk/N4631/data/SOLSDIR/L192989_SAP000_SB000_uv_123A9AE4Dt_120MHz.pre-cal.ms/killMS.DDS0.sols.npz
 - 09:51:31 - ClassInterpol             |   /data/amisk/N4631/data/SOLSDIR/L192989_SAP000_SB000_uv_123A9AE4Dt_130MHz.pre-cal.ms/killMS.DDS0.sols.npz
 - 09:51:31 - ClassInterpol             |   /data/amisk/N4631/data/SOLSDIR/L192989_SAP000_SB000_uv_123A9AE4Dt_139MHz.pre-cal.ms/killMS.DDS0.sols.npz
 - 09:51:31 - ClassInterpol             |   /data/amisk/N4631/data/SOLSDIR/L192989_SAP000_SB000_uv_123A9AE4Dt_148MHz.pre-cal.ms/killMS.DDS0.sols.npz
 - 09:51:31 - ClassInterpol             |   /data/amisk/N4631/data/SOLSDIR/L192989_SAP000_SB000_uv_123A9AE4Dt_158MHz.pre-cal.ms/killMS.DDS0.sols.npz
 - 09:51:31 - ClassInterpol             |   /data/amisk/N4631/data/SOLSDIR/L192989_SAP000_SB000_uv_123A9AE4Dt_167MHz.pre-cal.ms/killMS.DDS0.sols.npz
 - 09:51:31 - ClassInterpol             |   /data/amisk/N4631/data/SOLSDIR/L192989_SAP000_SB000_uv_123A9AE4Dt_177MHz.pre-cal.ms/killMS.DDS0.sols.npz
 - 09:51:32 - ClassInterpol             |   Sorting in frequency
 - 09:51:32 - ClassInterpol             |   Solution channel width is 2.343750 MHz for each solution file
 - 09:51:32 - ClassInterpol             |   Checking solution conformity
Traceback (most recent call last):
  File "/opt/soft/killms/killMS/MergeSols.py", line 200, in <module>
    main(options=options)
  File "/opt/soft/killms/killMS/MergeSols.py", line 192, in main
    CM=ClassMergeSols(ListSolsFile)
  File "/opt/soft/killms/killMS/MergeSols.py", line 54, in __init__
    self.CheckConformity()
  File "/opt/soft/killms/killMS/MergeSols.py", line 59, in CheckConformity
    C0=np.allclose(self.ListJonesSols[0].t0,self.ListJonesSols[iSol].t0)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/numeric.py", line 2270, in allclose
    res = all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan))
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/numeric.py", line 2366, in isclose
    return within_tol(x, y, atol, rtol)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/numeric.py", line 2352, in within_tol
    return less_equal(abs(x-y), atol + rtol * abs(y))
ValueError: operands could not be broadcast together with shapes (508,) (332,)
 - 09:51:32 - ClearSHM                  | Clear shared memory
 - 09:51:32 - ClearSHM                  | Clear Semaphores
 - 09:51:32 - ClearSHM                  | Clear shared dictionaries
FAILED to run MergeSols.py --SolsFilesIn=solslist_4873026783.005561.txt --SolFileOut=DDS0_4873026783.005561_merged.npz: return value is 1

```
Might it have something to do with the dataset?
I don't know why, I didn't have anything to do with the observation, but it has been observed for 12 minutes, then there is a 4 minute gap, then again 12 minutes, 4 minute gap and so on.
Cyril said that the Kalman Filter is sensitive to time gaps. Would this be the reason? Or something completely different?

Oh, and this is not in any of the log files ... only on the terminal output.

thx.

**Comment by twshimwell** [comment]
Not entirely sure but it looks like the solution files have different time durations. Could it be possible that the files have durations times? (these are ones you concatenated yourself I guess). Maybe one is missing some 12min observations at the start and end?

Or maybe it is something due to the gaps in the datasets... 

Can you check the shape of the killMS.DDS0.sols.npz for the different datasets?

**Comment by amisk** [comment]
Ah, sorry. Yes, they are there. And indeed, all except for the 177 MHz measurement sets have a shape of 508, and 177 has 332. Also, in the measurement sets itself, all have 30481 seconds, except for 177, which has 19921 seconds.

I guess I will just delete the 177 MHz set, and restart from the beginning.

**Comment by twshimwell** [comment]
Goodo. Probably no need to start at the beginning. Just remove it from mslist.txt and big-mslist.txt

**Comment by amisk** [comment]
Thanks!

It appears to run now further than before.
