### ISSUE TITLE
IOError: Not enough free space to write

### ISSUE THREAD

**Issue by fvitello** [mhardcastle/ddf-pipeline#124]
Hi, 

I have tried to run the pipeline with the tier1-jul2018-NVSS.cfg configuration file; after few minutes of run the execution stop with the following:

```
 - 08:23:18 - AsyncProcessPool          | [io00] [6.8/14.0 7.7/14.8 19.4Gb] process io00: exception raised processing job DATA:0:0: Traceback (most recent call last):
  File "/opt/DDFacet/DDFacet/Other/AsyncProcessPool.py", line 850, in _dispatch_job
    result = call(*args, **kwargs)
  File "/opt/DDFacet/DDFacet/Data/ClassVisServer.py", line 483, in _handler_LoadVisChunk
    read_data=bool(self.ColName), sort_by_baseline=self.GD["Data"]["Sort"])
  File "/opt/DDFacet/DDFacet/Data/ClassMS.py", line 538, in GiveChunk
    return self.ReadData(DATA, row0, row1, use_cache=use_cache, read_data=read_data, sort_by_baseline=sort_by_baseline)
  File "/opt/DDFacet/DDFacet/Data/ClassMS.py", line 765, in ReadData
    DOT_UVW=dot_uvw if dot_uvw is not None else np.array([]))
  File "/usr/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 574, in savez
    _savez(file, args, kwds, False)
  File "/usr/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 639, in _savez
    pickle_kwargs=pickle_kwargs)
  File "/usr/lib/python2.7/dist-packages/numpy/lib/format.py", line 584, in write_array
    array.tofile(fp)
IOError: Not enough free space to write 163155480 bytes
```

Free space on my disk (mounted via nfs) is about 4 TB of free space, can you help me to understand the issue?

Thanks

**Comment by cyriltasse** [comment]
it's a numpy wierdness, fixed by https://github.com/numpy/numpy/issues/5336#issuecomment-123436239

**Comment by cyriltasse** [comment]
where `TMPDIR` points to where there is space...

**Comment by fvitello** [comment]
Many thanks, this solved the issue
