### ISSUE TITLE
offsets.py failure

### ISSUE THREAD

**Issue by agwilber** [mhardcastle/ddf-pipeline#128]
Hey everyone, 
I am getting this error during the offset correction: 

============================== Offset correction =============================

Hex tiling image
Number of hexes across 10.645299228203363
Number of hexes up 10.618575217691872
Running: offsets.py tier1-jul2018-NVSS.cfg
Determining astrometric offsets with method panstarrs in mode normal
Merging downloaded catalogues
WARNING: W21: None:3:0: W21: vo.table is designed for VOTable version 1.1, 1.2 and 1.3, but this file is 1.0 [astropy.io.votable.exceptions]
WARNING: W42: None:3:0: W42: No XML namespace specified [astropy.io.votable.exceptions]
Traceback (most recent call last):
  File "/hs/fs06/data/AG_Brueggen/Amanda/Wirtinger_Pack/ddf-pipeline/scripts/offsets.py", line 445, in <module>
    do_offsets(o)
  File "/hs/fs06/data/AG_Brueggen/Amanda/Wirtinger_Pack/ddf-pipeline/scripts/offsets.py", line 394, in do_offsets
    data=merge_cat(method,**kwargs)
  File "/hs/fs06/data/AG_Brueggen/Amanda/Wirtinger_Pack/ddf-pipeline/scripts/offsets.py", line 370, in merge_cat
    t2=unique(t,keys=['ra','dec'])
  File "/home/hslxrsrv3/sttf310/.local/lib/python2.7/site-packages/astropy/table/operations.py", line 388, in unique
    grouped_table = input_table.group_by(keys)
  File "/home/hslxrsrv3/sttf310/.local/lib/python2.7/site-packages/astropy/table/table.py", line 2666, in group_by
    return groups.table_group_by(self, keys)
  File "/home/hslxrsrv3/sttf310/.local/lib/python2.7/site-packages/astropy/table/groups.py", line 22, in table_group_by
    return _table_group_by(table, keys)
  File "/home/hslxrsrv3/sttf310/.local/lib/python2.7/site-packages/astropy/table/groups.py", line 85, in _table_group_by
    diffs = np.concatenate(([True], table_keys[1:] != table_keys[:-1], [True]))
  File "/home/hslxrsrv3/sttf310/.local/lib/python2.7/site-packages/astropy/table/table.py", line 2630, in __ne__
    return ~self.__eq__(other)
  File "/home/hslxrsrv3/sttf310/.local/lib/python2.7/site-packages/numpy/ma/core.py", line 3016, in __array_finalize__
    self._fill_value = _check_fill_value(self._fill_value, self.dtype)
  File "/home/hslxrsrv3/sttf310/.local/lib/python2.7/site-packages/numpy/ma/core.py", line 476, in _check_fill_value
    fill_value = np.array(fill_value, copy=False, dtype=ndtype)
ValueError: Can't cast from structure to non-structure, except if the structure only has a single field.
 - 09:26:52 - ClearSHM                  | Clear shared memory
 - 09:26:52 - ClearSHM                  | Clear Semaphores
 - 09:26:52 - ClearSHM                  | Clear shared dictionaries
FAILED to run offsets.py tier1-jul2018-NVSS.cfg: return value is 1
Traceback (most recent call last):
  File "/hs/fs06/data/AG_Brueggen/Amanda/Wirtinger_Pack/ddf-pipeline/scripts/pipeline.py", line 1482, in <module>
    main(o)
  File "/hs/fs06/data/AG_Brueggen/Amanda/Wirtinger_Pack/ddf-pipeline/scripts/pipeline.py", line 1392, in main
    run('offsets.py '+' '.join(sys.argv[1:]),log=None)
  File "/hs/fs06/data/AG_Brueggen/Amanda/Wirtinger_Pack/ddf-pipeline/utils/auxcodes.py", line 54, in run
    die('FAILED to run '+s+': return value is '+str(retval))
  File "/hs/fs06/data/AG_Brueggen/Amanda/Wirtinger_Pack/ddf-pipeline/utils/auxcodes.py", line 36, in die
    raise Exception(s)
Exception: FAILED to run offsets.py tier1-jul2018-NVSS.cfg: return value is 1

**Comment by mhardcastle** [comment]
Strange error message! OK, let's check the basics. In your working directory do you have a directory 'panstarrs' and does it contain about 120 files with names like `panstarrs-xxx.vo`? And do those files have sensible-looking XML data in ... like the excerpt below?

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE VOTABLE SYSTEM "http://cdsweb.u-strasbg.fr/xml/VOTable.dtd">
<VOTABLE version="1.0">
 <DESCRIPTION>
   Mikulski Archive for Space Telescopes (MAST)    archive.stsci.edu
   send questions to: archive@stsci.edu
 </DESCRIPTION>
<DEFINITIONS>
  <COOSYS ID="myJ2000" system="eq_FK5" equinox="2000." epoch="2000."/>
</DEFINITIONS>
<RESOURCE type="results">
<INFO name="QUERY_STATUS" value="OK"></INFO>
<PARAM ID="param_max_records" name="max_records" datatype="int" value="100000"></PARAM>
<PARAM ID="param_ndetections" datatype="char" name="ndetections" value="&gt;+5" arraysize="*"></PARAM>
<PARAM ID="param_RA" name="RA" datatype="float" unit="deg" value="223.771750025"></PARAM>
<PARAM ID="param_DEC" name="DEC" datatype="float" unit="deg" value="51.1484730327"></PARAM>
<PARAM ID="param_verb" name="verb" datatype="int" value="1"></PARAM>
<PARAM ID="param_ordercolumn1" datatype="char" name="ordercolumn1" value="ang_sep" arraysize="*"></PARAM>
<PARAM ID="param_ordercolumn2" datatype="char" name="ordercolumn2" value="objid" arraysize="*"></PARAM>
<PARAM ID="param_ordercolumn3" datatype="char" name="ordercolumn3" value="null" arraysize="*"></PARAM>
<PARAM ID="param_maxsr" name="maxsr" datatype="float" value="0.5"></PARAM>
<PARAM ID="param_sr" name="sr" datatype="float" unit="deg" value="0.5"></PARAM>
<PARAM ID="param_coordformat" datatype="char" name="coordformat" value="sex" arraysize="*"></PARAM>
<PARAM ID="param_mission" datatype="char" name="mission" value="panstarrs" arraysize="*"></PARAM>
<PARAM ID="param_found_rows" name="found_rows" datatype="int" value="10892"></PARAM>
<TABLE name="PANSTARRS">
<DESCRIPTION>MAST PANSTARRS Search: 10892 row(s) returned!</DESCRIPTION>
<FIELD ID="objid" name="objID" datatype="char" ucd="ID_MAIN" arraysize="*" ><DESCRIPTION>Unique object identifier
 </DESCRIPTION>
</FIELD>
<FIELD ID="ramean" name="raMean" datatype="double" ucd="POS_EQ_RA_MAIN" unit="deg" ref="myJ2000" ><DESCRIPTION>Right ascension from single epoch detections (weighted mean </DESCRIPTION>
</FIELD>
<FIELD ID="decmean" name="decMean" datatype="double" ucd="POS_EQ_DEC_MAIN" unit="deg" ref="myJ2000" ><DESCRIPTION>Declination from single epoch detections (weighted mean </DESCRIPTION>
</FIELD>
<DATA>
<TABLEDATA>
<TR>
<TD>1.69382237556814e+17</TD><TD>223.755683333</TD><TD>51.1527777778</TD>
</TR>
<TR>
<TD>1.693622377903169e+17</TD><TD>223.779025</TD><TD>51.1385055556</TD>
</TR>
</pre>
```
Also, what version of astropy are you using?

**Comment by mhardcastle** [comment]
Closing this as there was no response -- may have been related to issue #153, in which case trying again with the `pslocal` offset mode might be the solution.
