### ISSUE TITLE
OSError: [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by fvitello** [mhardcastle/ddf-pipeline#130]
Hi, 

I have tried to run the pipeline with the tier1-jul2018-NVSS.cfg configuration file; but unfortunately execution stop with the following:

```
2018-11-17 07:40:35: Traceback (most recent call last):
2018-11-17 07:40:35:   File "/opt/DDFacet/DDFacet/DDF.py", line 387, in <module>
2018-11-17 07:40:35:     main(OP, messages)
2018-11-17 07:40:35:   File "/opt/DDFacet/DDFacet/DDF.py", line 235, in main
2018-11-17 07:40:35:     Imager.main()
2018-11-17 07:40:35:   File "/opt/DDFacet/DDFacet/Imager/ClassDeconvMachine.py", line 1090, in main
2018-11-17 07:40:35:     repMinor, continue_deconv, update_model = self.DeconvMachine.Deconvolve()
2018-11-17 07:40:35:   File "/opt/DDFacet/DDFacet/Imager/SSD/ClassImageDeconvMachineSSD.py", line 409, in Deconvolve
2018-11-17 07:40:35:     self.DeconvListIsland(ListSmallIslands,ParallelMode="OverIslands",ListInitIslands=ListInitSmallIslands)
2018-11-17 07:40:35:   File "/opt/DDFacet/DDFacet/Imager/SSD/ClassImageDeconvMachineSSD.py", line 552, in DeconvListIsland
2018-11-17 07:40:35:     workerlist[ii].start()
2018-11-17 07:40:35:   File "/usr/lib/python2.7/multiprocessing/process.py", line 130, in start
2018-11-17 07:40:35:     self._popen = Popen(self)
2018-11-17 07:40:35:   File "/usr/lib/python2.7/multiprocessing/forking.py", line 121, in __init__
2018-11-17 07:40:35:     self.pid = os.fork()
2018-11-17 07:40:35: OSError: [Errno 12] Cannot allocate memory
2018-11-17 07:40:41: Traceback (most recent call last):
2018-11-17 07:40:41:   File "/opt/DDFacet/DDFacet/Array/NpShared.py", line 130, in GiveArray
2018-11-17 07:40:41:     return SharedArray.attach(Name)
2018-11-17 07:40:41: OSError: [Errno 2] No such file or directory: 'file:///dev/shm/ddf.44459/DicoInitIsland/int:26:d/str:S:a'
2018-11-17 07:40:41: Traceback (most recent call last):
2018-11-17 07:40:41:   File "/opt/DDFacet/DDFacet/Array/NpShared.py", line 130, in GiveArray
2018-11-17 07:40:41:     return SharedArray.attach(Name)
2018-11-17 07:40:41: OSError: [Errno 2] No such file or directory: 'file:///dev/shm/ddf.44459/DicoInitIsland/int:26:d/str:Alpha:a'
2018-11-17 07:40:41: Process WorkerDeconvIsland-145:
2018-11-17 07:40:41: Traceback (most recent call last):
2018-11-17 07:40:41:   File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
2018-11-17 07:40:41:     self.run()
2018-11-17 07:40:41:   File "/opt/DDFacet/DDFacet/Imager/SSD/ClassImageDeconvMachineSSD.py", line 805, in run
2018-11-17 07:40:41:     Model=CEv.main(NGen=NGen,NIndiv=NIndiv,DoPlot=False)
2018-11-17 07:40:41:   File "/opt/DDFacet/DDFacet/Imager/SSD/GA/ClassEvolveGA.py", line 174, in main
2018-11-17 07:40:41:     self.ArrayMethodsMachine.PM.ReinitPop(pop0,SModelArrayMP,AlphaModel=AModelArrayMP)
2018-11-17 07:40:41:   File "/opt/DDFacet/DDFacet/Imager/SSD/ClassParamMachine.py", line 108, in ReinitPop
2018-11-17 07:40:41:     SigVal=DicoSigma["Value"]*np.max(np.abs(SModelArray))
2018-11-17 07:40:41: TypeError: bad operand type for abs(): 'NoneType'
2018-11-17 07:40:41: Exception OSError: (2, 'No such file or directory', '/dev/shm/ddf.44459/DeconvListIslands/int:19:d/str:Chains:d') in <bound method ClassArrayMethodSSD.__del__ of <DDFacet.Imager.SSD.ClassArrayMethodSSD.ClassArrayMethodSSD instance at 0x7f911a62e878>> ignored
2018-11-17 07:40:41: Error loading file:///dev/shm/ddf.44459/DicoInitIsland/int:26:d/str:S:a
2018-11-17 07:40:41: Error loading file:///dev/shm/ddf.44459/DicoInitIsland/int:26:d/str:Alpha:a
2018-11-17 07:40:41: Traceback (most recent call last):
2018-11-17 07:40:41:   File "/opt/DDFacet/DDFacet/Array/NpShared.py", line 130, in GiveArray
2018-11-17 07:40:41:     return SharedArray.attach(Name)
2018-11-17 07:40:41: OSError: [Errno 2] No such file or directory: 'file:///dev/shm/ddf.44459/DicoInitIsland/int:28:d/str:S:a'
2018-11-17 07:40:41: Traceback (most recent call last):
2018-11-17 07:40:41:   File "/opt/DDFacet/DDFacet/Array/NpShared.py", line 130, in GiveArray
2018-11-17 07:40:41:     return SharedArray.attach(Name)
2018-11-17 07:40:41: OSError: [Errno 2] No such file or directory: 'file:///dev/shm/ddf.44459/DicoInitIsland/int:28:d/str:Alpha:a'

```

the error seems to be **2018-11-17 07:40:35: OSError: [Errno 12] Cannot allocate memory**, but i cannot understand why. The computational resources have 256GB of RAM and 256g of shm:
tmpfs                                            268435456   116810988  151624468  44% /dev/shm

Can you help me to understand the issue?

Thanks

**Comment by twshimwell** [comment]
This does look like a normal memory error. You monitor the job with MemMonitor.py (this comes with DDFacet) but you are sure you are able to put 256GB into /dev/shm?

**Comment by fvitello** [comment]
> Also check whether there are other processes running on the machine that might be using the memory.
> 
> Make sure /dev/shm is clear before starting the run.

No other process is running on the machine but shm is not empty. Now i tried to free the space in shm and tu run again the pipeline, I will let you know.
