### ISSUE TITLE
bug in pol cube reprocessing part

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#137]
Hmm for the reprocessing im stumbling into the error below. I guess you are not seeing this though @mhardcastle? Seems like my naming convention has a number after ".cube"...

Making uncorrected cube
Output file shape is (480, 2, 6075, 6075)
Traceback (most recent call last):
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline-DR2/ddf-pipeline/scripts/pipeline.py", line 1753, in <module>
    main(o)
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline-DR2/ddf-pipeline/scripts/pipeline.py", line 1640, in main
    do_polcubes(colname,CurrentDDkMSSolName,low_uvrange,'image_full_low',ddf_kw,beamsize=o['low_psf_arcsec'],imsize=low_imsize,cellsize=o['low_cell'],robust=o['low_robust'],options=o,catcher=catcher)
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline-DR2/ddf-pipeline/scripts/do_polcubes.py", line 95, in do_polcubes
    freqs,hdus=get_freqs_hdus('%s_QU_Cube*.cube.SmoothNorm.fits'%imageoutname)
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline-DR2/ddf-pipeline/scripts/do_polcubes.py", line 20, in get_freqs_hdus
    freqs,hdus = (list(x) for x in zip(*sorted(zip(freqs, hdus), key=lambda pair: pair[0])))

**Comment by mhardcastle** [comment]
Not sure I see what the actual error is here? But no, I haven't seen this, but I don't remake any pol cubes in reprocessing since the .fz files are still there. If there is a simple file name bug then it should be easy to fix.

**Comment by twshimwell** [comment]
OK ill try a fix. I think I just add another *

**Comment by twshimwell** [comment]
Was related to the SmoothNorm files which are no longer uploaded.
