### ISSUE TITLE
strange beam response error

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#143]
Not sure if this is really a problem with DDFacet or the LOFAR beam libraries. But when trying to image a field at dec -20 I get the following error with the LOFAR beam. The error occurs at the image_dirin_init_SSD step and ive attached the full log.

019-01-10 04:44:03:  - 04:44:03 - AsyncProcessPool          | [io00] [1.7/3.6 2.8/4.6 15.5Gb] process io00: exception raised processing job DATA:0:0: Traceback (most recent call last):
2019-01-10 04:44:03:   File "/net/para10/data1/shimwell/software/killmsddf/new-install/DDFacet/DDFacet/Other/AsyncProcessPool.py", line 850, in _dispatch_job
2019-01-10 04:44:03:     result = call(*args, **kwargs)
2019-01-10 04:44:03:   File "/net/para10/data1/shimwell/software/killmsddf/new-install/DDFacet/DDFacet/Data/ClassVisServer.py", line 533, in _handler_LoadVisChunk
2019-01-10 04:44:03:     JonesMachine.InitDDESols(DATA)
2019-01-10 04:44:03:   File "/net/para10/data1/shimwell/software/killmsddf/new-install/DDFacet/DDFacet/Data/ClassJones.py", line 92, in InitDDESols
2019-01-10 04:44:03:     DicoSols, TimeMapping, DicoClusterDirs = self.MakeSols("Beam", DATA, quiet=quiet)
2019-01-10 04:44:03:   File "/net/para10/data1/shimwell/software/killmsddf/new-install/DDFacet/DDFacet/Data/ClassJones.py", line 243, in MakeSols
2019-01-10 04:44:03:     DicoSols = self.GiveBeam(DATA["uniq_times"], quiet=quiet)
2019-01-10 04:44:03:   File "/net/para10/data1/shimwell/software/killmsddf/new-install/DDFacet/DDFacet/Data/ClassJones.py", line 687, in GiveBeam
2019-01-10 04:44:03:     self.InitBeamMachine()
2019-01-10 04:44:03:   File "/net/para10/data1/shimwell/software/killmsddf/new-install/DDFacet/DDFacet/Data/ClassJones.py", line 668, in InitBeamMachine
2019-01-10 04:44:03:     self.BeamMachine = ClassLOFARBeam.ClassLOFARBeam(self.MS, self.GD)
2019-01-10 04:44:03:   File "/net/para10/data1/shimwell/software/killmsddf/new-install/DDFacet/DDFacet/Data/ClassLOFARBeam.py", line 33, in __init__
2019-01-10 04:44:03:     self.InitLOFARBeam()
2019-01-10 04:44:03:   File "/net/para10/data1/shimwell/software/killmsddf/new-install/DDFacet/DDFacet/Data/ClassLOFARBeam.py", line 44, in InitLOFARBeam
2019-01-10 04:44:03:     import lofar.stationresponse as lsr
2019-01-10 04:44:03:   File "/net/lofar1/data1/sweijen/software/LOFAR/2018_11_20/lofar/lib64/python2.7/site-packages/lofar/stationresponse/__init__.py", line 22, in <module>
2019-01-10 04:44:03:     from ._stationresponse import StationResponse
2019-01-10 04:44:03: ImportError: /net/lofar1/data1/sweijen/software/LOFAR/2018_11_20/lofar/lib64/libstationresponse.so: undefined symbol: _ZN4casa4UnitC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
2019-01-10 04:44:03: 

[DDF-image_dirin_SSD_init.log](https://github.com/mhardcastle/ddf-pipeline/files/2744581/DDF-image_dirin_SSD_init.log)

**Comment by mhardcastle** [comment]
But it happens on `import lofar.stationresponse as lsr`, hard to see how it can depend on dec...

**Comment by twshimwell** [comment]
ok maybe i wasnt sourcing exactly the same thing for runs that work. My mistake.
