### ISSUE TITLE
And another, different, killms slow smooth problem

### ISSUE THREAD

**Issue by mhardcastle** [mhardcastle/ddf-pipeline#145]
Similar reprocessing problem:

```
Running: kMS.py --MSName L369494_SB000_uv.dppp.pre-cal_126DA1CB3t_121MHz.pre-cal.ms --SolverType KAFCA --PolMode Scalar --BaseImageName image_full_ampphase_di_m --dt 43.630000 --NIterKF 6 --CovQ 0.100000 --LambdaKF=0.500000 --NCPU 32 --OutSolsName DDS3_full_slow --PowerSmooth=0.000000 --InCol DATA_DI_CORRECTED --Weighting Natural --UVMinMax=0.500000,1000.000000 --SolsDir=SOLSDIR --PreApplySols=[DDS3_full_smoothed] --NChanSols 1 --BeamMode LOFAR --LOFARBeamMode=A --DDFCacheDir=. --NodesFile image_dirin_SSD_m.npy.ClusterCat.npy --DicoModel image_full_ampphase_di_m_masked.DicoModel
 - 16:11:07 - AsyncProcessPool          |   Fixing parent process to vthread 0
 - 16:11:07 - AsyncProcessPool          |   Worker affinities not specified, leaving unset
       __        _   __   __   ____    ____   ______     
      [  |  _   (_) [  | [  | |_   \  /   _|.' ____ \    
       | | / ]  __   | |  | |   |   \/   |  | (___ \_|   
       | '' <  [  |  | |  | |   | |\  /| |   _.____`.    
       | |`\ \  | |  | |  | |  _| |_\/_| |_ | \____) |   
      [__|  \_][___][___][___]|_____||_____| \______.'   
             This is version : v2.5-597-gc7cfada
                                                        
[...]
 - 16:15:01 - ClassVisServer            |   Taking antenna #06[CS004HBA0] out of the solve (~100.0% of flagged data, more than 90.0%)
 - 16:15:01 - ClassVisServer            |   Taking antenna #07[CS004HBA1] out of the solve (~100.0% of flagged data, more than 90.0%)
 - 16:15:02 - ClassVisServer            |   Taking antenna #34[CS103HBA0] out of the solve (~100.0% of flagged data, more than 90.0%)
 - 16:15:02 - ClassVisServer            |   Taking antenna #35[CS103HBA1] out of the solve (~100.0% of flagged data, more than 90.0%)
 - 16:15:41 - ClassVisServer            |   Update LOFAR beam in 44 directions [Dt = 5.0 min] ... 
 - 16:15:54 - ClassVisServer            |          .... done Update LOFAR beam 
 - 16:15:54 - ClassVisServer            |   Loading solution file DDS3_full_smoothed in AP mode
 - 16:15:59 - ClassJonesDomains         |   Merging Jones arrays
 - 16:15:59 - ClassJonesDomains         |   Compute frequency domains of merged Jones arrays
 - 16:15:59 - ClassJonesDomains         |     There are 1 channels in the merged Jones array
 - 16:15:59 - killMS                    |   Traceback (most recent call last):
  File "/home/mjh/pipeline-master/killMS/kMS.py", line 1169, in <module>
    main(OP=OP,MSName=MSName)
  File "/home/mjh/pipeline-master/killMS/kMS.py", line 616, in main
    Load=VS.LoadNextVisChunk()
  File "/home/mjh/pipeline-master/killMS/Data/ClassVisServer.py", line 1034, in LoadNextVisChunk
    DicoJones=DomainsMachine.MergeJones(DicoJones1,DicoJones)
  File "/home/mjh/pipeline-master/killMS/Data/ClassJonesDomains.py", line 204, in MergeJones
    DicoOut["Jones"][itime,:,:,ich,:,:]=ModLinAlg.BatchDot(G0,G1)
  File "/home/mjh/pipeline-master/killMS/Array/ModLinAlg.py", line 120, in BatchDot
    C00[:]=a0*a1+c0*b1
ValueError: operands could not be broadcast together with shapes (2610,) (2552,) 

Traceback (most recent call last):
  File "/home/mjh/pipeline-master/killMS/kMS.py", line 1169, in <module>
    main(OP=OP,MSName=MSName)
  File "/home/mjh/pipeline-master/killMS/kMS.py", line 616, in main
    Load=VS.LoadNextVisChunk()
  File "/home/mjh/pipeline-master/killMS/Data/ClassVisServer.py", line 1034, in LoadNextVisChunk
    DicoJones=DomainsMachine.MergeJones(DicoJones1,DicoJones)
  File "/home/mjh/pipeline-master/killMS/Data/ClassJonesDomains.py", line 204, in MergeJones
    DicoOut["Jones"][itime,:,:,ich,:,:]=ModLinAlg.BatchDot(G0,G1)
  File "/home/mjh/pipeline-master/killMS/Array/ModLinAlg.py", line 120, in BatchDot
    C00[:]=a0*a1+c0*b1
ValueError: operands could not be broadcast together with shapes (2610,) (2552,) 
```

With all .ddfcache cleared, of course.

This one's in `/beegfs/car/mjh/P245+40`.

**Comment by cyriltasse** [comment]
ok - I'll try to reproduce - which node can I use?

**Comment by mhardcastle** [comment]
You can use node011.

**Comment by twshimwell** [comment]
Any joy on this one either? I'm hitting this problem on a field too.

**Comment by cyriltasse** [comment]
Sorry - I didn't have time to take a look at this one. I'll push the changes to test the other one.

**Comment by cyriltasse** [comment]
So it seems it's a number of direction problem `Update LOFAR beam in 44 direction`... `kMS` has removed an empty direction from the skymodel...

**Comment by mhardcastle** [comment]
... it didn't, so this is still open. The field is still pretty crappy but I'm not sure why kMS decides to remove an empty direction and then won't apply the solutions properly...

**Comment by cyriltasse** [comment]
Super weird.... in `logs/KillMS-L369494_SB000_uv.dppp.pre-cal_126DA1CB3t_121MHz.pre-cal.ms_DDS3_full.log` it also removes a direction and doesn't crash. Doesn't mean it does the right thing...

**Comment by cyriltasse** [comment]
The facet without sources is dominated by the artifacts of a neigbooring (3C?) source:

![image](https://user-images.githubusercontent.com/6523227/52470986-f0190500-2b8f-11e9-867a-eaaede4e1def.png)

**Comment by mhardcastle** [comment]
Sure, I know it's a crappy field, but it's weird that the slow smooth can't cope with dropping a facet whereas the DDS3_full runs fine.
