### ISSUE TITLE
error clearing semaphores

### ISSUE THREAD

**Issue by amisk** [mhardcastle/ddf-pipeline#173]
Hi,

On a different machine I installed the pipeline using only master branches.
When I try to run it, it crashes right at the beginning.
```
Running: CleanSHM.py
 - 13:10:06 - ClearSHM                  | Clear shared memory
 - 13:10:06 - ClearSHM                  | Clear Semaphores
Traceback (most recent call last):
  File "/opt/soft/ddfacet/DDFacet/DDFacet/CleanSHM.py", line 65, in <module>
    _pyGridderSmear.pyDeleteSemaphore(ListSemaphores)
TypeError: pyDeleteSemaphore(): incompatible function arguments. The following argument types are supported:
    1. () -> None

Invoked with: []
 - 13:10:06 - ClearSHM                  | Clear shared memory
 - 13:10:06 - ClearSHM                  | Clear Semaphores
Traceback (most recent call last):
  File "/opt/soft/ddfacet/DDFacet/DDFacet/CleanSHM.py", line 65, in <module>
    _pyGridderSmear.pyDeleteSemaphore(ListSemaphores)
TypeError: pyDeleteSemaphore(): incompatible function arguments. The following argument types are supported:
    1. () -> None

Invoked with: []
FAILED to run CleanSHM.py: return value is 1
Traceback (most recent call last):
  File "/opt/soft/ddf/ddf-pipeline/scripts/pipeline.py", line 1767, in <module>
    main(o)
  File "/opt/soft/ddf/ddf-pipeline/scripts/pipeline.py", line 949, in main
    run('CleanSHM.py',dryrun=o['dryrun'])
  File "/opt/soft/ddf/ddf-pipeline/utils/auxcodes.py", line 54, in run
    die('FAILED to run '+s+': return value is '+str(retval))
  File "/opt/soft/ddf/ddf-pipeline/utils/auxcodes.py", line 36, in die
    raise Exception(s)
Exception: FAILED to run CleanSHM.py: return value is 1

```
Is it possible that the master branch (of ddfacet) is old, and therefor incompatible to some package that is used?

**Comment by mhardcastle** [comment]
It *is* old, but that looks like an internal DDFacet build problem, because I think the issue is with the call to the C gridder library. (Or with the version of the build tools used not working properly.)

**Comment by mhardcastle** [comment]
Any followup on this?

**Comment by amisk** [comment]
Didn't see it since then ... yeah, close it.
