### ISSUE TITLE
Connection aborted in panstarrs download

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#179]
not sure whats happening here but this is for a field in the HETDEX region and ive tried a few times but keep getting the same error. Not sure if anyone has ideas or has seen this before?

Catalogue at position (190.91910635126135, 49.420004586052194) already present
Downloading at position (203.1713908928821, 50.14131736827938)
Traceback (most recent call last):
  File "/opt/lofar/ddf-pipeline/scripts/pipeline.py", line 1748, in <module>
    main(o)
  File "/opt/lofar/ddf-pipeline/scripts/pipeline.py", line 1594, in main
    get_cat(o['method'])
  File "/opt/lofar/ddf-pipeline/utils/get_cat.py", line 57, in get_cat
    r = requests.post('http://archive.stsci.edu/panstarrs/search.php', data = {'ra':p[0],'dec':p[1],'SR':CSIZE,'max_records':100000,'nDetections':">+5",'action':'Search','selectedColumnsCsv':'objid,ramean,decmean'},timeout=300)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))

**Comment by mhardcastle** [comment]
The remote panstarrs server is failing for some reason. Use `method='pslocal'` instead of `method='panstarrs'`. This was discussed in issue #153.

**Comment by mhardcastle** [comment]
(don't know how well this is tested by anyone other than me but let me know if it doesn't work for some reason).
