### ISSUE TITLE
"Massive if" looks for one of the products it skips

### ISSUE THREAD

**Issue by tikk3r** [mhardcastle/ddf-pipeline#182]
I was trying out a run with the `inputmodel` functionality to skip some initial steps, but it crashed with

```
 - 01:21:59 - MakeMask                  | Compute noise map...
 - 01:22:02 - ClassCasaImage            |   ----> Save data in casa image as FITS file image_full_low_im.app.restored.fits.noise.fits
 - 01:22:04 - ClassCasaImage            |   ----> Save data in casa image as FITS file image_full_low_im.app.restored.fits.noise.mean.fits
 - 01:22:07 - ClassCasaImage            |   ----> Save data in casa image as FITS file image_full_low_im.app.restored.fits.rmsmapmask.fits
Traceback (most recent call last):
  File "/opt/lofar/ddf-pipeline/scripts/pipeline.py", line 1811, in <module>
    main(o)
  File "/opt/lofar/ddf-pipeline/scripts/pipeline.py", line 1580, in main
    make_extended_mask('image_full_low_im.app.restored.fits','image_dirin_SSD.app.restored.fits',rmsthresh=o['extended_rms'],sizethresh=1500,rootname='full',rmsfacet=o['rmsfacet'])
  File "/opt/lofar/ddf-pipeline/utils/make_extended_mask.py", line 43, in make_extended_mask
    get_rms_map2(infile,ds9region,prefix+'rms-low.fits')
  File "/opt/lofar/ddf-pipeline/utils/auxcodes.py", line 233, in get_rms_map2
    polylist = convert_regionfile_to_poly(ds9region)
  File "/opt/lofar/ddf-pipeline/utils/auxcodes.py", line 195, in convert_regionfile_to_poly
    cra,cdec=get_centpos()
  File "/opt/lofar/ddf-pipeline/utils/auxcodes.py", line 292, in get_centpos
    raise RuntimeError('Cannot find image with central RA, DEC in working directory')
RuntimeError: Cannot find image with central RA, DEC in working directory
```

It looks like it still looks for one of the first images to make the mask after `image_full_low`. It looks for `image_dirin_SSD` in
https://github.com/mhardcastle/ddf-pipeline/blob/0b5e56545917eeffe17a8daf6f88af79c4b6321d/utils/auxcodes.py#L287-L292
and
https://github.com/mhardcastle/ddf-pipeline/blob/d999a4c02d44907cfe223a20025b12064b484094/scripts/pipeline.py#L1580

Is this a bug or was I supposed to provide these files myself from a previous run?

**Comment by mhardcastle** [comment]
That's a bug, although you can work round it by providing an image. It's also lazy programming because we could get the central position from the MSs with very little effort, but this way we don't have to pass around the mslist. Do you have any images with WCS in the working directory at this point?

**Comment by tikk3r** [comment]
I got it running again by

- Adding a `ds9region='image_full_ampphase_di.tessel.reg'` in the call to `make_extended_mask` in `pipeline.py` to override the default `image_dirin_SSD_m_c.tessel.reg`. A vimdiff on these region files from a previous run seem to indicate these are the same.
- Adding `image_full_ampphase_di.dirty.fits` to the `checklist` variable in `auxcodes.py`'s `get_centpos()` function.

It's making `image_full_low_im_m` now.

**Comment by mhardcastle** [comment]
Thanks. Could you submit a PR for your working version please?

**Comment by tikk3r** [comment]
Reopening, because I just saw it crash again at offset corrections. It looks for `image_ampphase1.app.restored.fits`. Is there a specific reason for that image or would it be safe to replace that with e.g. `image_full_ampphase_di.app.restored.fits` as well?

**Comment by mhardcastle** [comment]
What's the traceback? Not sure why the offsets code should be looking at that at all.

**Comment by tikk3r** [comment]
```
pixels above 6.5e-06 Jy (based on max DR setting of 1e+06)
 - 06:26:37 - ClassCasaImage            | [io00] [4.0/11.9 5.7/13.6 73.7Gb]   ----> Save image data as FITS file image_full_ampphase_di_m.NS.alpha.fits
 - 06:26:47 - DDFacet                   | [79.5/162.0 83.7/166.2 51.4Gb] DDFacet ended successfully after 1154m51.9s

============================== Offset correction =============================

Retrying download for some or all of the catalogue
Traceback (most recent call last):
  File "./pipeline.py", line 1813, in <module>
    main(o)
  File "./pipeline.py", line 1657, in main
    get_cat(o['method'])
  File "/opt/lofar/ddf-pipeline/utils/get_cat.py", line 45, in get_cat
    ra_factor,pos=tile(cwd+'/image_ampphase1.app.restored.fits')
  File "/opt/lofar/ddf-pipeline/utils/get_cat.py", line 15, in tile
    return hextile(file,CSIZE*0.9)
  File "/opt/lofar/ddf-pipeline/utils/hextile.py", line 15, in hextile
    hdus=fits.open(image)
  File "/usr/lib64/python2.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 148, in fitsopen
    lazy_load_hdus, **kwargs)
  File "/usr/lib64/python2.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 402, in fromfile
    lazy_load_hdus=lazy_load_hdus, **kwargs)
  File "/usr/lib64/python2.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 1006, in _readfrom
    fileobj = _File(fileobj, mode=mode, memmap=memmap, cache=cache)
  File "/usr/lib64/python2.7/site-packages/astropy/utils/decorators.py", line 522, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/astropy/io/fits/file.py", line 150, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/usr/lib64/python2.7/site-packages/astropy/io/fits/file.py", line 506, in _open_filename
    self._file = fileobj_open(self.name, IO_FITS_MODES[mode])
  File "/usr/lib64/python2.7/site-packages/astropy/io/fits/util.py", line 395, in fileobj_open
    return open(filename, mode)
IOError: [Errno 2]
```

**Comment by mhardcastle** [comment]
Ah right. Not where I was looking. Yeah, that code only uses the WCS, so it's the same situation as before. In fact what we want is a single function in utils that finds a suitable full-resolution file to get the WCS from, and then we could import and use that wherever needed. If you'd like to implement that feel free, otherwise I'll have a look later today.

**Comment by mhardcastle** [comment]
OK, try the latest master version, which should do something sensible...

**Comment by tikk3r** [comment]
The latest master fixes it.

**Comment by tikk3r** [comment]
Another crash unfortunately
```
--> Wrote FITS file 'image_full_ampphase_di_m.NS.offset_cat.fits'
--> Wrote FITS file 'image_full_ampphase_di_m.NS.offset_gaul.fits'
14946 LOFAR sources before filtering
11876 LOFAR sources after filtering
Set up structure
Traceback (most recent call last):
  File "/net/lofar1/data1/sweijen/software/LOFAR/DDF_2019_04_01/ddf-pipeline/scripts/offsets.py", line 459, in <module>
    do_offsets(o)
  File "/net/lofar1/data1/sweijen/software/LOFAR/DDF_2019_04_01/ddf-pipeline/scripts/offsets.py", line 437, in do_offsets
    NDir=np.load("image_dirin_SSD_m.npy.ClusterCat.npy").shape[0]
  File "/net/lofar1/data1/sweijen/software/LOFAR/lofarenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 415, in load
    fid = open(os_fspath(file), "rb")
IOError: [Errno 2] No such file or directory: 'image_dirin_SSD_m.npy.ClusterCat.npy'
 - 13:29:30 - ClearSHM                  | Clear shared memory
 - 13:29:30 - ClearSHM                  | Clear Semaphores
 - 13:29:30 - ClearSHM                  | Clear shared dictionaries
FAILED to run offsets.py ./tier1-jul2018.cfg: return value is 1
Traceback (most recent call last):
  File "/net/lofar1/data1/sweijen/software/LOFAR/DDF_2019_04_01/ddf-pipeline/scripts/pipeline.py", line 1819, in <module>
    main(o)
  File "/net/lofar1/data1/sweijen/software/LOFAR/DDF_2019_04_01/ddf-pipeline/scripts/pipeline.py", line 1672, in main
    run('offsets.py '+' '.join(sys.argv[1:]),log=None)
  File "/net/lofar1/data1/sweijen/software/LOFAR/DDF_2019_04_01/ddf-pipeline/utils/auxcodes.py", line 54, in run
    die('FAILED to run '+s+': return value is '+str(retval))
  File "/net/lofar1/data1/sweijen/software/LOFAR/DDF_2019_04_01/ddf-pipeline/utils/auxcodes.py", line 36, in die
    raise Exception(s)
Exception: FAILED to run offsets.py ./tier1-jul2018.cfg: return value is 1
```

**Comment by mhardcastle** [comment]
Right, you should have a ClusterCat of course so it's just a matter of using the correct one. I guess @twshimwell didn't do the offsets when he was running this branch.

**Comment by twshimwell** [comment]
Ah yeh I just copied this file from the run of the single field that I used to get the model and directions file

**Comment by mhardcastle** [comment]
But some ClusterCat must exist by the time it's running offsets. I guess maybe it's just an issue of what it's called.

**Comment by tikk3r** [comment]
Yeah it just seems to be names in a couple of locations that it usually takes from the now skipped steps, nothing fundamentally wrong. Maybe it's my bad and I misunderstood that that ClusterCat is something that I had to copy over myself as well.

**Comment by mhardcastle** [comment]
I think the issue here was the same as #197 which was fixed a while ago. Closing.
