### ISSUE TITLE
Failed to run bootstrap.py

### ISSUE THREAD

**Issue by mooneyse** [mhardcastle/ddf-pipeline#198]
Hi,

I was hoping to get some advice as to why this crashed at the start of `bootstrap.py`. 
How would `o['low_psf_arcsec']` be `NoneType`? Here is the traceback:
```
============================== Bootstrap =============================

Running bootstrap
Running: bootstrap.py oj287.cfg
Traceback (most recent call last):
  File "/opt/lofar/ddf-pipeline/scripts/bootstrap.py", line 252, in <module>
    run_bootstrap(o)
  File "/opt/lofar/ddf-pipeline/scripts/bootstrap.py", line 63, in run_bootstrap
    low_uvrange=[o['image_uvmin'],2.5*206.0/o['low_psf_arcsec']]
TypeError: unsupported operand type(s) for /: 'float' and 'NoneType'
 - 19:50:42 - ClearSHM                  | Clear shared memory
 - 19:50:42 - ClearSHM                  | Clear Semaphores
 - 19:50:42 - ClearSHM                  | Clear shared dictionaries
FAILED to run bootstrap.py oj287.cfg: return value is 1
Traceback (most recent call last):
  File "/opt/lofar/ddf-pipeline/scripts/pipeline.py", line 1819, in <module>
    main(o)
  File "/opt/lofar/ddf-pipeline/scripts/pipeline.py", line 1213, in main
    run('bootstrap.py '+' '.join(sys.argv[1:]),log=None,dryrun=o["dryrun"])
  File "/opt/lofar/ddf-pipeline/utils/auxcodes.py", line 54, in run
    die('FAILED to run '+s+': return value is '+str(retval))
  File "/opt/lofar/ddf-pipeline/utils/auxcodes.py", line 36, in die
    raise Exception(s)
Exception: FAILED to run bootstrap.py oj287.cfg: return value is 1
```

This data has been through Prefactor by Tim as part of the co-observing scheme. Here is the relevant section in `oj287.cfg`:
```INI
[bootstrap]
catalogues = ['/opt/lofar/DDFCatalogues/VLSS.fits', '/opt/lofar/DDFCatalogues/wenss.fits', '/opt/lofar/DDFCatalogues/B2.fits']
names = ['VLSS', 'WENSS', 'B2']
radii = [40, 40, 40]
frequencies=[74e6, 327e6, 408e6]
groups=[1,2,2]
```

Cheers.

**Comment by twshimwell** [comment]
Do you have the whole parset?

**Comment by mooneyse** [comment]
Ah yep, I know what you are thinking and you are correct! I misspelt `low_psf_arcsec` in `oj287.cfg`; hadn't thought to look in the `[image]` section. :+1:
