### ISSUE TITLE
 "'NoneType' object has no attribute 'getpid'"

### ISSUE THREAD

**Issue by fvitello** [mhardcastle/ddf-pipeline#222]
Hi, 

i am experiencing the following error running the DDF-pipeline with DDFacet version is 0.3.4.1.

Can you help me to fix it?

Thanks

```
- 18:54:57 - AsyncProcessPool          | [0.1/1.0 1.8/2.8 0.1Gb] waiting for worker processes to start up
Process comp01:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/DDFacet/Other/AsyncProcessPool.py", line 808, in _start_worker
    psutil.Process().cpu_affinity(affinity)
  File "/usr/local/lib/python2.7/dist-packages/psutil/__init__.py", line 837, in cpu_affinity
    self._proc.cpu_affinity_set(list(set(cpus)))
  File "/usr/local/lib/python2.7/dist-packages/psutil/_pslinux.py", line 1516, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/psutil/_pslinux.py", line 1954, in cpu_affinity_set
    cext.proc_cpu_affinity_set(self.pid, cpus)
OSError: [Errno 22] Invalid argument

....


Warning: setupterm: could not find terminfo database
    Load weights.................   0/6 [                                                  ]  00%  - 0'00" 
 - 18:55:02 - AsyncProcessPool          | [TB] [0.1/0.1 1.8/1.8 0.2Gb] worker 'comp09' died with exit code 1
 - 18:55:02 - AsyncProcessPool          | [TB] [0.1/0.1 1.8/1.8 0.2Gb] worker 'comp10' died with exit code 1
 - 18:55:02 - AsyncProcessPool          | [TB] [0.1/0.1 1.8/1.8 0.2Gb] worker 'comp11' died with exit code 1
 - 18:55:02 - AsyncProcessPool          | [TB] [0.1/0.1 1.8/1.8 0.2Gb] worker 'comp01' died with exit code 1
 - 18:55:02 - AsyncProcessPool          | [TB] [0.1/0.1 1.8/1.8 0.2Gb] worker 'comp02' died with exit code 1
 - 18:55:02 - AsyncProcessPool          | [TB] [0.1/0.1 1.8/1.8 0.2Gb] worker 'comp03' died with exit code 1
 - 18:55:02 - AsyncProcessPool          | [TB] [0.1/0.1 1.8/1.8 0.2Gb] worker 'comp05' died with exit code 1
 - 18:55:02 - AsyncProcessPool          | [TB] [0.1/0.1 1.8/1.8 0.2Gb] worker 'comp06' died with exit code 1
 - 18:55:02 - AsyncProcessPool          | [TB] [0.1/0.1 1.8/1.8 0.2Gb] worker 'comp07' died with exit code 1
 - 18:55:02 - AsyncProcessPool          | [TB] [0.1/0.1 1.8/1.8 0.2Gb] 9 worker(s) have died. Initiating shutdown.
 - 18:55:02 - DDFacet                   | [0.1/1.0 1.8/2.8 0.2Gb] A worker process has died on us unexpectedly. This probably indicates a bug:
 - 18:55:02 - DDFacet                   | [0.1/1.0 1.8/2.8 0.2Gb]   the original underlying error may be reported in the log [possibly far] above.
 - 18:55:02 - DDFacet                   | [0.1/1.0 1.8/2.8 0.2Gb] 
 - 18:55:02 - DDFacet                   | [0.1/1.0 1.8/2.8 0.2Gb] There was a problem after 0m34.5s; if you think this is a bug please open an issue, 
- 18:55:02 - DDFacet                   | [0.1/1.0 1.8/2.8 0.2Gb]   quote your version of DDFacet and attach your logfile.
 - 18:55:02 - DDFacet                   | [0.1/1.0 1.8/2.8 0.2Gb] You are using DDFacet revision: 0.3.4.1
 - 18:55:02 - DDFacet                   | [0.1/1.0 1.8/2.8 0.2Gb] Your logfile is available here: /archive/home/marbondi/euclid-deep-field-lofar-it/output_data/day3/ddfpipeline/image_dirin_SSD_init.log
Exception AttributeError: "'NoneType' object has no attribute 'getpid'" in <bound method AsyncProcessPool.__del__ of <DDFacet.Other.AsyncProcessPool.AsyncProcessPool object at 0x7f32159048d0>> ignored
Exception AttributeError: "'NoneType' object has no attribute 'SharedDict'" in <bound method ClassImageDeconvMachine.__del__ of <DDFacet.Imager.MSMF.ClassImageDeconvMachineMSMF.ClassImageDeconvMachine instance at 0x7f32051c62d8>> ignored
Exception AttributeError: "'NoneType' object has no attribute 'SharedDict'" in <bound method ClassImageDeconvMachine.__del__ of <DDFacet.Imager.MSMF.ClassImageDeconvMachineMSMF.ClassImageDeconvMachine instance at 0x7f32051aa128>> ignored

```

**Comment by mhardcastle** [comment]
This is a DDFacet error not a ddf-pipeline error -- to do with DDF's CPU affinity code. My first suggestion would be to try pulling a recent version of saopicc's DDFacet and running with that. If the problem persists then you could also try the `ddf_pipeline_fixes_may18` branch of DDFacet from cyriltasse's repository, assuming you have access; that's the 'stable' branch that is very well tested with ddf-pipeline.

**Comment by mhardcastle** [comment]
Closing this issue in the absence of further discussion.
