### ISSUE TITLE
ValueError: HuberRegressor convergence failed: l-BFGS-b solver terminated with ABNORMAL_TERMINATION_IN_LNSRCH

### ISSUE THREAD

**Issue by AlexKurek** [mhardcastle/ddf-pipeline#242]
It happens when Im trying to do point a) regarding flux calibration. Im using data I processed earlier by DDF pipeline (P24Hetdex20).

> --> Wrote FITS file 'image_full_ampphase_di_m.NS_shift.int.facetRestoredcorrectedfluxcat.srl.fits'
> --> Wrote ds9 region file 'image_full_ampphase_di_m.NS_shift.int.facetRestoredcorrectedfluxcat.srl.reg'
> original length: 21672
> filter around 187.40696 45.33236
> filter to 1.0 deg: 3890
> 3890 region filtered
> Scaling factor being used for field catalogue 9.516
> isolated sources 3890
> snr  more than 7 sources 1426
> Compact sources len 1348
> original length: 21763
> filter to 1.0 deg: 3894
> isolated sources 2825
> snr  more than 7 sources 1043
> After cross match 989
> /usr/local/lib/python2.7/dist-packages/sklearn/model_selection/_validation.py:544: FutureWarning: From version 0.22, errors during fit will result in a cross validation score of NaN by default. Use error_score='raise' if you want an exception raised or error_score=np.nan to adopt the behavior from version 0.22.
>   FutureWarning)
> LinearRegression Gradient [9.51650522] intercept 0.0 Mean MAE: 1.166 (1.067)
> Traceback (most recent call last):
>   File "./ddf-pipeline/scripts/align-extrationimage-fluxes.py", line 243, in <module>
>     modelname,gradient,intercept,mae,maestd = plot_best_fit(X, y, xaxis, model)
>   File "./ddf-pipeline/scripts/align-extrationimage-fluxes.py", line 123, in plot_best_fit
>     results = evaluate_model(X, y, model)
>   File "./ddf-pipeline/scripts/align-extrationimage-fluxes.py", line 101, in evaluate_model
>     scores = cross_val_score(model, X, y, scoring='neg_mean_absolute_error', cv=cv, n_jobs=-1)
>   File "/usr/local/lib/python2.7/dist-packages/sklearn/model_selection/_validation.py", line 404, in cross_val_score
>     error_score=error_score)
>   File "/usr/local/lib/python2.7/dist-packages/sklearn/model_selection/_validation.py", line 241, in cross_validate
>     for train, test in cv.split(X, y, groups))
>   File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/parallel.py", line 934, in __call__
>     self.retrieve()
>   File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/parallel.py", line 862, in retrieve
>     raise exception.unwrap(this_report)
> sklearn.externals.joblib.my_exceptions.JoblibValueError: JoblibValueError
> ___________________________________________________________________________
> ...........................................................................
> /storage/kurek/fluxCal/c/P24Hetdex20/ddf-pipeline/scripts/align-extrationimage-fluxes.py in <module>()
>     238 xaxis = arange(X.min(), X.max(), 0.01)
>     239 
>     240 bestmae = 10000.0
>     241 for model in get_models():
>     242     # plot the line of best fit
> --> 243     modelname,gradient,intercept,mae,maestd = plot_best_fit(X, y, xaxis, model)
>     244     if mae < bestmae:
>     245         bestmodel,bestgradient,bestintercept,bestmae,bestmaestd = modelname,gradient,intercept,mae,maestd 
>     246 
>     247 # plot the dataset
> 
> ...........................................................................
> /storage/kurek/fluxCal/c/P24Hetdex20/ddf-pipeline/scripts/align-extrationimage-fluxes.py in plot_best_fit(X=<Column name='cutout_Total_flux' dtype='float64'...64818177402
>  89.14183283458438
>  36.13305736234389, y=<Column name='Total_flux' dtype='float64' unit='...66000977616
>  848.2736812539049
>  343.8421738600645, xaxis=array([7.36758356e+00, 7.37758356e+00, 7.3875835... 1.53267476e+04, 1.53267576e+04, 1.53267676e+04]), model=HuberRegressor(alpha=0.0001, epsilon=1.35, fit_i...ax_iter=100,
>         tol=1e-05, warm_start=False))
>     118 	# calculate outputs for grid across the domain
>     119 	yaxis = model.predict(xaxis.reshape((len(xaxis), 1)))
>     120 	# plot the line of best fit
>     121 	pyplot.plot(xaxis, yaxis, label=type(model).__name__)
>     122  
> --> 123         results = evaluate_model(X, y, model)
>         results = undefined
>         X = <Column name='cutout_Total_flux' dtype='float64'...64818177402
>  89.14183283458438
>  36.13305736234389
>         y = <Column name='Total_flux' dtype='float64' unit='...66000977616
>  848.2736812539049
>  343.8421738600645
>         model = HuberRegressor(alpha=0.0001, epsilon=1.35, fit_i...ax_iter=100,
>         tol=1e-05, warm_start=False)
>     124 
>     125         gradient = model.coef_
>     126         intercept = model.intercept_
>     127         modelname =  type(model).__name__
> 
> ...........................................................................
> /storage/kurek/fluxCal/c/P24Hetdex20/ddf-pipeline/scripts/align-extrationimage-fluxes.py in evaluate_model(X=<Column name='cutout_Total_flux' dtype='float64'...64818177402
>  89.14183283458438
>  36.13305736234389, y=<Column name='Total_flux' dtype='float64' unit='...66000977616
>  848.2736812539049
>  343.8421738600645, model=HuberRegressor(alpha=0.0001, epsilon=1.35, fit_i...ax_iter=100,
>         tol=1e-05, warm_start=False))
>      96 
>      97 def evaluate_model(X, y, model):
>      98 	# define model evaluation method
>      99 	cv = RepeatedKFold(n_splits=5, n_repeats=3, random_state=1)
>     100 	# evaluate model
> --> 101 	scores = cross_val_score(model, X, y, scoring='neg_mean_absolute_error', cv=cv, n_jobs=-1)
>         scores = undefined
>         model = HuberRegressor(alpha=0.0001, epsilon=1.35, fit_i...ax_iter=100,
>         tol=1e-05, warm_start=False)
>         X = <Column name='cutout_Total_flux' dtype='float64'...64818177402
>  89.14183283458438
>  36.13305736234389
>         y = <Column name='Total_flux' dtype='float64' unit='...66000977616
>  848.2736812539049
>  343.8421738600645
>         cv = <sklearn.model_selection._split.RepeatedKFold object>
>     102 	# force scores to be positive
>     103 	return absolute(scores)
>     104 
>     105 # dictionary of model names and model objects
> 
> ...........................................................................
> /usr/local/lib/python2.7/dist-packages/sklearn/model_selection/_validation.py in cross_val_score(estimator=HuberRegressor(alpha=0.0001, epsilon=1.35, fit_i...ax_iter=100,
>         tol=1e-05, warm_start=False), X=<Column name='cutout_Total_flux' dtype='float64'...64818177402
>  89.14183283458438
>  36.13305736234389, y=<Column name='Total_flux' dtype='float64' unit='...66000977616
>  848.2736812539049
>  343.8421738600645, groups=None, scoring='neg_mean_absolute_error', cv=<sklearn.model_selection._split.RepeatedKFold object>, n_jobs=-1, verbose=0, fit_params=None, pre_dispatch='2*n_jobs', error_score='raise-deprecating')
>     399                                 scoring={'score': scorer}, cv=cv,
>     400                                 return_train_score=False,
>     401                                 n_jobs=n_jobs, verbose=verbose,
>     402                                 fit_params=fit_params,
>     403                                 pre_dispatch=pre_dispatch,
> --> 404                                 error_score=error_score)
>         error_score = 'raise-deprecating'
>     405     return cv_results['test_score']
>     406 
>     407 
>     408 def _fit_and_score(estimator, X, y, scorer, train, test, verbose,
> 
> ...........................................................................
> /usr/local/lib/python2.7/dist-packages/sklearn/model_selection/_validation.py in cross_validate(estimator=HuberRegressor(alpha=0.0001, epsilon=1.35, fit_i...ax_iter=100,
>         tol=1e-05, warm_start=False), X=<Column name='cutout_Total_flux' dtype='float64'...64818177402
>  89.14183283458438
>  36.13305736234389, y=<Column name='Total_flux' dtype='float64' unit='...66000977616
>  848.2736812539049
>  343.8421738600645, groups=None, scoring={'score': make_scorer(mean_absolute_error, greater_is_better=False)}, cv=<sklearn.model_selection._split.RepeatedKFold object>, n_jobs=-1, verbose=0, fit_params=None, pre_dispatch='2*n_jobs', return_train_score=False, return_estimator=False, error_score='raise-deprecating')
>     236         delayed(_fit_and_score)(
>     237             clone(estimator), X, y, scorers, train, test, verbose, None,
>     238             fit_params, return_train_score=return_train_score,
>     239             return_times=True, return_estimator=return_estimator,
>     240             error_score=error_score)
> --> 241         for train, test in cv.split(X, y, groups))
>         cv.split = <bound method RepeatedKFold.split of <sklearn.model_selection._split.RepeatedKFold object>>
>         X = <Column name='cutout_Total_flux' dtype='float64'...64818177402
>  89.14183283458438
>  36.13305736234389
>         y = <Column name='Total_flux' dtype='float64' unit='...66000977616
>  848.2736812539049
>  343.8421738600645
>         groups = None
>     242 
>     243     zipped_scores = list(zip(*scores))
>     244     if return_train_score:
>     245         train_scores = zipped_scores.pop(0)
> 
> ...........................................................................
> /usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/parallel.py in __call__(self=Parallel(n_jobs=-1), iterable=<generator object <genexpr>>)
>     929                 # No need to wait for async callbacks to trigger to
>     930                 # consumption.
>     931                 self._iterating = False
>     932 
>     933             with self._backend.retrieval_context():
> --> 934                 self.retrieve()
>         self.retrieve = <bound method Parallel.retrieve of Parallel(n_jobs=-1)>
>     935             # Make sure that we get a last message telling us we are done
>     936             elapsed_time = time.time() - self._start_time
>     937             self._print('Done %3i out of %3i | elapsed: %s finished',
>     938                         (len(self._output), len(self._output),
> 
> ---------------------------------------------------------------------------
> Joblib worker traceback:
> ---------------------------------------------------------------------------
> ValueError                                         Fri Mar  5 02:13:26 2021
> PID: 24064                                   Python 2.7.17: /usr/bin/python
> ...........................................................................
> /usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/parallel.py in __call__(self=<sklearn.externals.joblib.parallel.BatchedCalls object>)
>     220     def __call__(self):
>     221         # Set the default nested backend to self._backend but do not set the
>     222         # change the default number of processes to -1
>     223         with parallel_backend(self._backend, n_jobs=self._n_jobs):
>     224             return [func(*args, **kwargs)
> --> 225                     for func, args, kwargs in self.items]
>         func = <function _fit_and_score>
>         args = (HuberRegressor(alpha=0.0001, epsilon=1.35, fit_i...ax_iter=100,
>         tol=1e-05, warm_start=False), <Column name='cutout_Total_flux' dtype='float64'...64818177402
>  89.14183283458438
>  36.13305736234389, <Column name='Total_flux' dtype='float64' unit='...66000977616
>  848.2736812539049
>  343.8421738600645, {'score': make_scorer(mean_absolute_error, greater_is_better=False)}, array([  0,   3,   4,   5,   6,   7,   8,  10,  ...77, 978, 979, 981, 982, 984, 985, 986, 987, 988]), array([  1,   2,   9,  11,  14,  16,  21,  24,  ..., 952, 957, 958, 971, 975, 976,
>        980, 983]), 0, None, None)
>         kwargs = {'error_score': 'raise-deprecating', 'return_estimator': False, 'return_times': True, 'return_train_score': False}
>         self.items = [(<function _fit_and_score>, (HuberRegressor(alpha=0.0001, epsilon=1.35, fit_i...ax_iter=100,
>         tol=1e-05, warm_start=False), <Column name='cutout_Total_flux' dtype='float64'...64818177402
>  89.14183283458438
>  36.13305736234389, <Column name='Total_flux' dtype='float64' unit='...66000977616
>  848.2736812539049
>  343.8421738600645, {'score': make_scorer(mean_absolute_error, greater_is_better=False)}, array([  0,   3,   4,   5,   6,   7,   8,  10,  ...77, 978, 979, 981, 982, 984, 985, 986, 987, 988]), array([  1,   2,   9,  11,  14,  16,  21,  24,  ..., 952, 957, 958, 971, 975, 976,
>        980, 983]), 0, None, None), {'error_score': 'raise-deprecating', 'return_estimator': False, 'return_times': True, 'return_train_score': False})]
>     226 
>     227     def __len__(self):
>     228         return self._size
>     229 
> 
> ...........................................................................
> /usr/local/lib/python2.7/dist-packages/sklearn/model_selection/_validation.py in _fit_and_score(estimator=HuberRegressor(alpha=0.0001, epsilon=1.35, fit_i...ax_iter=100,
>         tol=1e-05, warm_start=False), X=<Column name='cutout_Total_flux' dtype='float64'...64818177402
>  89.14183283458438
>  36.13305736234389, y=<Column name='Total_flux' dtype='float64' unit='...66000977616
>  848.2736812539049
>  343.8421738600645, scorer={'score': make_scorer(mean_absolute_error, greater_is_better=False)}, train=array([  0,   3,   4,   5,   6,   7,   8,  10,  ...77, 978, 979, 981, 982, 984, 985, 986, 987, 988]), test=array([  1,   2,   9,  11,  14,  16,  21,  24,  ..., 952, 957, 958, 971, 975, 976,
>        980, 983]), verbose=0, parameters=None, fit_params={}, return_train_score=False, return_parameters=False, return_n_test_samples=False, return_times=True, return_estimator=False, error_score='raise-deprecating')
>     525 
>     526     try:
>     527         if y_train is None:
>     528             estimator.fit(X_train, **fit_params)
>     529         else:
> --> 530             estimator.fit(X_train, y_train, **fit_params)
>         estimator.fit = <bound method HuberRegressor.fit of HuberRegress...x_iter=100,
>         tol=1e-05, warm_start=False)>
>         X_train = <Column name='cutout_Total_flux' dtype='float64'...64818177402
>  89.14183283458438
>  36.13305736234389
>         y_train = <Column name='Total_flux' dtype='float64' unit='...66000977616
>  848.2736812539049
>  343.8421738600645
>         fit_params = {}
>     531 
>     532     except Exception as e:
>     533         # Note fit time as time until error
>     534         fit_time = time.time() - start_time
> 
> ...........................................................................
> /usr/local/lib/python2.7/dist-packages/sklearn/linear_model/huber.py in fit(self=HuberRegressor(alpha=0.0001, epsilon=1.35, fit_i...ax_iter=100,
>         tol=1e-05, warm_start=False), X=array([[1.75921349e+01],
>        [4.61907644e+01]...      [8.91418328e+01],
>        [3.61330574e+01]]), y=<Column name='Total_flux' dtype='float64' unit='...66000977616
>  848.2736812539049
>  343.8421738600645, sample_weight=<Column name='Total_flux' dtype='float64' unit='....
> 1.0
> 1.0
> 1.0
> 1.0
> 1.0
> 1.0
> 1.0
> 1.0
> 1.0
> 1.0
> 1.0
> 1.0)
>     288             maxiter=self.max_iter, pgtol=self.tol, bounds=bounds,
>     289             iprint=0)
>     290         if dict_['warnflag'] == 2:
>     291             raise ValueError("HuberRegressor convergence failed:"
>     292                              " l-BFGS-b solver terminated with %s"
> --> 293                              % dict_['task'].decode('ascii'))
>         dict_.decode = undefined
>     294         # In scipy <= 1.0.0, nit may exceed maxiter.
>     295         # See https://github.com/scipy/scipy/issues/7854.
>     296         self.n_iter_ = min(dict_['nit'], self.max_iter)
>     297         self.scale_ = parameters[-1]
> 
> ValueError: HuberRegressor convergence failed: l-BFGS-b solver terminated with ABNORMAL_TERMINATION_IN_LNSRCH
> ___________________________________________________________________________
>

**Comment by twshimwell** [comment]
Hey,

The image for this one is supposed to be the extracted image and the region file is the region file corresponding to that extract. Seems like your region file is pretty large (larger than 1x1deg). Also the scaling you are using is really big at a factor of 9.5. Not sure if these things are related to your issue but just wanted to check these inputs are the appropriate ones?

# fitsimage -- this is the image from the extract pipeline (should be about 6" resolution)
# catalogue -- this is the catalogue of LoTSS-DR2 (if field in lotss-DR2 or this is the catalogue from the lotss quality-pipeline if not in LoTSS-DR2)
# regionfile -- this is the region file that comes with the extract tar.gz file (so outside this region sources are subtracted)
# fieldname -- ONLY USE IF NOT USING LOTSS DR2 - this is the name of the LoTSS field if using the LoTSS database (i.e. PXXX+XX) or any fieldname if not using that.
# nodatabase -- ONLY USE IF NOT USING LOTSS DR2 - this means that  you have to provide a scaling factor rather than take from the LoTSS database automatically
# fieldfactor -- ONLY USE IF NOT USING LOTSS DR2 - this is the scaling factor that you multiply you catalogue by (so from the quality-pipeline the nvss_factor/5.9124 - if a lotss field this can be found on https://lofar-surveys.org/widefields.html and is the "scale" number in the table)

**Comment by AlexKurek** [comment]
I haven't don anything to the image. I just processed the data by DDF pipeline, did point c) and later b) and now Im trying to do a). As far as I understand, the script used original region file produced by DDF pipeline.
I got this large factor from point c):

> [92mPlotting flux ratios[0m
> [92mPlotting flux scale comparison[0m
> Median LOFAR/TGSS ratio is 1.965 (1-sigma 1.938 -- 1.998)
> **Median LOFAR/NVSS ratio is 9.516 (1-sigma 9.319 -- 9.857)**
> An estimate of the image noise is 120.030 muJy/beam
> Median dynamic range is 238.57386563347387
> Number of sources in full table is 13690
> Cutoff will be 0.002400600496912375 Jy
> Number of sources after completeness cut is 4978
> 0 3.335633422476484 -0.008622407304053947 0.008847894515645383
> 1 1.7863927498676664 -0.006236317199295627 0.006280177094984962
> for 0.100 Jy number count norm should be 812.643377
> measured number count norm is 1315.6361086045479
> scaling factor should be 1.618958754284203
> total factor is 1.618958754284203
> New flux norm value is 0.061768096151537485
> for 0.062 Jy number count norm should be 563.088810
> measured number count norm is 638.6782222166122
> scaling factor should be 1.1342406578929982
> total factor is 1.8362888425609432
> New flux norm value is 0.05445766356698929
> for 0.054 Jy number count norm should be 510.830195
> measured number count norm is 528.7182378037937
> scaling factor should be 1.0350175909465495
> total factor is 1.9005912541094552
> New flux norm value is 0.05261520581228614
> for 0.053 Jy number count norm should be 497.373038
> measured number count norm is 502.11442111323595
> scaling factor should be 1.0095328507971406
> total factor is 1.9187093069612309
> New flux norm value is 0.05211836917514915
> for 0.052 Jy number count norm should be 493.723270
> measured number count norm is 495.0191627199154
> scaling factor should be 1.002624734030677
> total factor is 1.923745408574189
> New flux norm value is 0.05198193043336042
> for 0.052 Jy number count norm should be 492.719410
> measured number count norm is 493.07659704657283
> scaling factor should be 1.0007249297750993
> total factor is 1.925139988900575
> New flux norm value is 0.05194427448214239
> for 0.052 Jy number count norm should be 492.442233
> measured number count norm is 492.54091363205265
> scaling factor should be 1.0002003910453403
> total factor is 1.9255257697153771
> New flux norm value is 0.0519338674001655
> for 0.052 Jy number count norm should be 492.365619
> measured number count norm is 492.392899525715
> scaling factor should be 1.0000554068418417
> total factor is 1.925632457017162
> New flux norm value is 0.05193099006801212
> Converged, stopping
> 120.03002484561875 238.57386563347387 13690 0.06757483585305249 0.0174113130074023 1.9650737553024014 9.516096737054582 3.335633422476484 1.7863927498676664 1.925632457017162

**Comment by twshimwell** [comment]
Ah right no this script is only to work on smaller images -- those from the run_extraction_pipeline and the run_wsclean scripts and not used for the regular DDF-pipeline outputs. For the DDF-pipeline output fluxscale the way we are aligning is to the use the quality-pipeline.py as youve done here.

So the line:

Median LOFAR/NVSS ratio is 9.516 (1-sigma 9.319 -- 9.857)

is the relevant one. Then to get the flux scale correction you take nvss_factor = 9.516. 

scaling_factor = 1.0/(nvss_factor/5.9124)

That is then the value you multiply you image by. Once multiplied you can e.g. check by running the quality_pipeline again on the new image and it should find a Median LOFAR/NVSS ratio of 1.0.

Note that your factor of 9.516 is very different to what we obtained when we processed P24Hetdex20 as part of DR2. There the value obtained was about 6.0.  Have you compared your map to the DR2 map?

**Comment by AlexKurek** [comment]
We have an extracted map for NGC6946, so now I tried to do:
`python3 ./ddf-pipeline/scripts/align-extrationimage-fluxes.py P311+61_NGC6946.dysco.sub.shift.avg.weights.ms.archive0.calibrated.fits-MFS-image.fits catalog.cat.fits catalog.cat.reg --fieldname ourField --nodatabase --fieldfactor 1.055`
on an extracted map. And I got:
```
[...]
--> Wrote FITS file 'P311+61_NGC6946.dysco.sub.shift.avg.weights.ms.archive0.calibratedcat.srl.fits-MFS-imagecat.srl.fits'
--> Wrote ds9 region file 'P311+61_NGC6946.dysco.sub.shift.avg.weights.ms.archive0.calibratedcat.srl.reg-MFS-imagecat.srl.reg'
original length: 9837
filter around 308.71804167 60.15367778
filter to 1.0 deg: 1103
148 region filtered
Scaling factor being used for field catalogue 1.055
isolated sources 148
snr  more than 7 sources 72
Compact sources len 62
original length: 29
filter to 1.0 deg: 29
isolated sources 14
snr  more than 7 sources 1
After cross match 1
Traceback (most recent call last):
  File "./ddf-pipeline/scripts/align-extrationimage-fluxes.py", line 279, in <module>
    modelname,gradient,intercept,mae,maestd = plot_best_fit(X, y, xaxis, model)
  File "./ddf-pipeline/scripts/align-extrationimage-fluxes.py", line 157, in plot_best_fit
    yaxis = model.predict(xaxis.reshape((len(xaxis), 1)))
  File "/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_base.py", line 362, in predict
    return self._decision_function(X)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_base.py", line 345, in _decision_function
    X = self._validate_data(X, accept_sparse=["csr", "csc", "coo"], reset=False)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/base.py", line 566, in _validate_data
    X = check_array(X, **check_params)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py", line 805, in check_array
    raise ValueError(
ValueError: Found array with 0 sample(s) (shape=(0, 1)) while a minimum of 1 is required.
```
Am I doing something wrong?

**Comment by mhardcastle** [comment]
I would guess this might be related to there being only one source in the list used for scaling.

**Comment by AlexKurek** [comment]
This is how it looks like. Is there something we should do in such cases?
![ds9](https://user-images.githubusercontent.com/45330694/163935923-d880cb01-b2f0-4b2f-aa2f-26bf787477a7.jpeg)

**Comment by twshimwell** [comment]
Does the comparison map look similar? Perhaps the extract/selfcal of your target hasn't worked too well. The extract/selfcal image should look comparable but slightly better than the associated wide field image.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AlexKurek** [comment]
Extracted map is on the left, map from DDF DR2 on the right. Scale is identical.
![Screenshot 2022-04-19 105019](https://user-images.githubusercontent.com/45330694/164157148-3d2faa54-d428-487d-8997-954591e4d354.png)

**Comment by mhardcastle** [comment]
Is this issue still live?

**Comment by AlexKurek** [comment]
Not for me. Maybe we should close it for now.
