### ISSUE TITLE
Bootstrap - ValueError: On entry to DLASCL parameter number 4 had an illegal value

### ISSUE THREAD

**Issue by henedler** [mhardcastle/ddf-pipeline#251]
Hi there,
I get an error in ddf-pipeline in the bootstrap step. Initially, I thought this might be specific to one data set (https://github.com/cyriltasse/DDFacet/issues/786), but now I also get this while processing multiple other observations, always at the same spot.
The error arises at the 'image_bootstrap_field' step, the previous step 'image_bootstrap_field_init' seems to run w/o errors, however the beam corrected diry image is fully NaN (image_bootstrap_field_init.dirty.corr-fits), not sure if this is related.

This is the error I get (see at the bottom for the full logs):
```
 - 23:47:21 - ClassInitSSDModel  [57.3/65.1 79.7/87.5 60.3Gb] Initialise HMP machine
 - 23:47:21 - ClassPSFServer     [57.3/65.1 79.7/87.5 60.3Gb] Using peak-normalised PSFs
 - 23:47:21 - CacheManager       [57.3/65.1 79.7/87.5 60.3Gb] cache element ./temp_mslist.txt.ddfcache/HMP_Init will be explicitly reset
 - 23:47:21 - ClassMultiScaleMac [57.3/65.1 79.7/87.5 60.3Gb] using auto PSF box of size 309x309 in minor cycle subtraction
 - 23:47:21 - ClassMultiScaleMac [56.6/65.1 79.0/87.5 60.3Gb] 48 scales and 7 scale functions in list
 - 23:47:57 - DDFacet            [58.0/65.1 80.4/87.5 61.5Gb] Traceback (most recent call last):
  File "/home/p1uy068/opt/src/DDFacet/build/lib/DDFacet/Array/ModLinAlg.py", line 229, in invSVD
    u,s,v=np.linalg.svd(Ar)
  File "<__array_function__ internals>", line 5, in svd
  File "/home/software/env/cuda-11.1.1_gcc-8.4.0_openmpi-4.0.5/pkgsrc/2020Q3/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 1661, in svd
    u, s, vh = gufunc(a, signature=signature, extobj=extobj)
ValueError: On entry to DLASCL parameter number 4 had an illegal value
```
So it looks like a NaN / Inf sneaked in somewhere and is causing trouble. 

I noticed that in the "brutal deconvolution" image (image_bootstrap_field.brutalRestored01.fits), there are NaN-squares, could this be causing the problem?
<img width="409" alt="grafik" src="https://user-images.githubusercontent.com/56255383/131222760-463ad768-e94c-47d2-ae2f-52fa55961456.png">
<img width="465" alt="grafik" src="https://user-images.githubusercontent.com/56255383/131222867-1b52e699-b210-4ff5-8a12-3e8b2a5889e8.png">

I greatly appreciate any help!

[image_bootstrap_field.log](https://github.com/mhardcastle/ddf-pipeline/files/7070924/image_bootstrap_field.log)

**Comment by mhardcastle** [comment]
Strange! This looks like a DDF problem. Which version of DDF are you running?

**Comment by henedler** [comment]
Hi Martin,
yes, it looks like some problem with DDF. 
I was running on the SlitHugeIslands branch, but I also tested with the current master, no difference.

**Comment by henedler** [comment]
Looks like the problem was caused because my MS files were not frequency concatenated and unevenly spaced in frequency. I suspect this caused some of the image channels to contain no data which might have lead to the issue.
Filling the frequency holes with dummy data solves the issue.
