### ISSUE TITLE
extract.py crash on NGC6946

### ISSUE THREAD

**Issue by AlexKurek** [mhardcastle/ddf-pipeline#277]
When I do:
```
export SDR_TOKEN= [hidden]
export RCLONE_CONFIG_DIR=/storage/akurek/extractPy/
export RCLONE_COMMAND= [hidden]
export SINGULARITYENV_NUMEXPR_MAX_THREADS=28
singularity exec -B /storage/akurek/extractPy/ /home/akurek/ddf-pipeline/ddf-py3.singularity.sif extraction.py --ncpu=28 NGC6946
```
Im getting:
```
[91m======================= Finding target name and position =======================[0m

Coordinate lookup gives ra=308.718050, dec=60.153678

[91m========================== Getting pointing positions ==========================[0m

We will use the following fields
 Field    ra    dec         sep        
                            deg        
------- ------ ----- ------------------
P311+61 311.83 60.63 1.6094202947607736

[91m=========================== Making working directory ===========================[0m


[91m============================ Downloading field data ============================[0m

[92mDoing field P311+61[0m
Trying rclone download for field P311+61
Running command maca_sksp_tape_DDF_readonly.conf --multi-thread-streams 1 --config=/storage/akurek/extractPy/maca_sksp_tape_DDF_readonly.conf listremotes
Traceback (most recent call last):
  File "/usr/local/src/ddf-pipeline/scripts/extraction.py", line 105, in <module>
    do_sdr_and_rclone_download(field,fdir,verbose=True)
  File "/usr/local/src/ddf-pipeline/scripts/run_extraction_pipeline.py", line 51, in do_sdr_and_rclone_download
    do_rclone_download(cname,f,verbose=verbose)
  File "/usr/local/src/ddf-pipeline/scripts/run_extraction_pipeline.py", line 63, in do_rclone_download
    rc.get_remote()
  File "/usr/local/src/ddf-pipeline/utils/rclone.py", line 116, in get_remote
    d=self.execute('listremotes')
  File "/usr/local/src/ddf-pipeline/utils/rclone.py", line 58, in execute
    proc=subprocess.Popen(fullcommand,stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'maca_sksp_tape_DDF_readonly.conf'
```
If I change my command to e.g.:
`singularity exec -B /storage/akurek/extractPy/ /home/akurek/ddf-pipeline/ddf-py3.singularity.sif extraction.py --ncpu=28 NGC4449`
(so only NGC6946 ---> NGC4449, everything else including directory structure, macaroon location etc. is identical) - its working. Its also working for N507. So far only N6946 is crashing.

**Comment by mhardcastle** [comment]
The error here is what the message says it is -- you haven't supplied the token file ('macaroon') needed to do rclone downloads for non-public areas of sky. P311+61 is not in DR2.

For collaborators, information on how to get the token is at https://lofar-surveys.org/collaborators.html .

**Comment by AlexKurek** [comment]
Solved
I had to remove
`export SINGULARITYENV_RCLONE_COMMAND=maca_sksp_tape_DDF_readonly.conf`
variable. Now its working.

**Comment by mhardcastle** [comment]
That is not a rclone command so that makes sense!
________________________________

**Comment by AlexKurek** [comment]
Yas, I thought I had to supply this file like this as a set of rclone commands.
Now its working:
```
 *                                        uv.tar: transferringTransferred:   	   19.848 GiB / 19.848 GiB, 100%, 0 B/s, ETA 0s
Checks:                 1 / 1, 100%
Transferred:            1 / 2, 50%
Elapsed time:     10m38.1s
Transferring:
 *                                        uv.tar: transferringTransferred:   	   19.848 GiB / 19.848 GiB, 100%, 0 B/s, ETA 0s
Checks:                 1 / 1, 100%
Transferred:            1 / 2, 50%
Elapsed time:     10m38.6s
Transferring:
 *                                        uv.tar: transferringTransferred:   	   19.848 GiB / 19.848 GiB, 100%, 0 B/s, ETA 0s
Checks:                 1 / 1, 100%
Transferred:            1 / 2, 50%
Elapsed time:     10m39.1s
Transferring:
 *                                        uv.tar: transferring
```
