### ISSUE TITLE
File not found! error when downloading files for extraction

### ISSUE THREAD

**Issue by AlexKurek** [mhardcastle/ddf-pipeline#288]
Using current master in Singularity container:

```
export SINGULARITYENV_RCLONE_CONFIG_DIR=/storage/kurek/
export SINGULARITYENV_NUMEXPR_MAX_THREADS=28
time singularity exec -B /storage/kurek/ /home/kurek/ddf-pipeline/ddf-py3.singularity_opt.sif extraction.py --timeavg=1 --overwriteoutput --ncpu=28 4C29.30 > logBash.txt 2>&1
```

Im getting:

```
Transferred:   	    1.117 MiB / 129.636 GiB, 0%, 0 B/s, ETA -
Transferred:            0 / 2, 0%
Elapsed time:         0.8s
Transferring:
 *                                    images.tar:  0% /11.128Gi, 0/s, -
 *                                        uv.tar:  0% /118.507Gi, 0/s, -Transferred:   	    5.992 MiB / 129.636 GiB, 0%, 0 B/s, ETA -
Transferred:            0 / 2, 0%
Elapsed time:         1.3s
```

[...]

 ```
*                                        uv.tar: 99% /118.507Gi, 11.156Mi/s, 0sTransferred:   	  129.636 GiB / 129.636 GiB, 100%, 11.127 MiB/s, ETA 0s
Transferred:            2 / 2, 100%
Elapsed time:   3h21m35.9s

[91m======================= Finding target name and position =======================[0m

Coordinate lookup gives ra=130.009733, dec=29.817425

[91m========================== Getting pointing positions ==========================[0m

We will use the following fields
    Field       ra    dec         sep        
                                  deg        
------------- ------ ----- ------------------
MS0839.8+2938 130.73 29.46 0.7208741710307898
      P130+32 130.71 31.91  2.177179197517556
      P129+29 129.86  29.4 0.4372534719774019

[91m=========================== Making working directory ===========================[0m


[91m============================ Downloading field data ============================[0m

[92mDoing field MS0839.8+2938[0m
Trying rclone download for field MS0839.8+2938
Macaroon maca_sksp_tape_DR2_readonly.conf does not exist!
Macaroon maca_sksp_tape_DDF.conf does not exist!
Running command rclone --multi-thread-streams 1 --config=/storage/kurek/maca_sksp_tape_DDF_readonly.conf listremotes
Running command rclone --multi-thread-streams 1 --config=/storage/kurek/maca_sksp_tape_DDF_readonly.conf -P --include-from /tmp/tmpskqtaoxg.txt copy maca_sksp_tape_DDF_readonly:other/MS0839.8+2938 /storage/kurek/4C29.30/4C29.30/MS0839.8+2938
Untarring files
[92mDoing field P130+32[0m
Initiating SDR download for field P130+32
Traceback (most recent call last):
  File "/usr/local/src/ddf-pipeline/scripts/extraction.py", line 106, in <module>
    do_sdr_and_rclone_download(field,fdir,verbose=True)
  File "/usr/local/src/ddf-pipeline/utils/reprocessing_utils.py", line 68, in do_sdr_and_rclone_download
    s.download_and_stage(cname,tarfiles)
  File "/usr/local/src/ddf-pipeline/utils/sdr_wrapper.py", line 102, in download_and_stage
    raise RuntimeError('File not found!')
RuntimeError: File not found!
```

So it crashes when trying to d/l second field.

**Comment by twshimwell** [comment]
Hey, the public ones in the SDR repository they are downloaded a different way require:

export SINGULARITYENV_SDR_TOKEN=0e72f595-6f97-942a-42a3-b7a2f6016020

thanks,

Tim

**Comment by AlexKurek** [comment]
Ok, so I understand for some objects I will need both token and macaroon file.
I added `SINGULARITYENV_SDR_TOKEN `and restarted - it crashed saying:

```
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Checks:                 2 / 2, 100%
Elapsed time:         0.4s

[91m======================= Finding target name and position =======================[0m

Coordinate lookup gives ra=130.009733, dec=29.817425

[91m========================== Getting pointing positions ==========================[0m

We will use the following fields
    Field       ra    dec         sep        
                                  deg        
------------- ------ ----- ------------------
MS0839.8+2938 130.73 29.46 0.7208741710307898
      P130+32 130.71 31.91  2.177179197517556
      P129+29 129.86  29.4 0.4372534719774019

[91m=========================== Making working directory ===========================[0m


[91m============================ Downloading field data ============================[0m

[92mDoing field MS0839.8+2938[0m
Trying rclone download for field MS0839.8+2938
Macaroon maca_sksp_tape_DR2_readonly.conf does not exist!
Macaroon maca_sksp_tape_DDF.conf does not exist!
Running command rclone --multi-thread-streams 1 --config=/storage/kurek/maca_sksp_tape_DDF_readonly.conf listremotes
Running command rclone --multi-thread-streams 1 --config=/storage/kurek/maca_sksp_tape_DDF_readonly.conf -P --include-from /tmp/tmpo3rx4yqe.txt copy maca_sksp_tape_DDF_readonly:other/MS0839.8+2938 /storage/kurek/4C29.30/4C29.30/MS0839.8+2938
Untarring files
[92mDoing field P130+32[0m
Initiating SDR download for field P130+32
Traceback (most recent call last):
  File "/usr/local/src/ddf-pipeline/scripts/extraction.py", line 106, in <module>
    do_sdr_and_rclone_download(field,fdir,verbose=True)
  File "/usr/local/src/ddf-pipeline/utils/reprocessing_utils.py", line 68, in do_sdr_and_rclone_download
    s.download_and_stage(cname,tarfiles)
  File "/usr/local/src/ddf-pipeline/utils/sdr_wrapper.py", line 102, in download_and_stage
    raise RuntimeError('File not found!')
RuntimeError: File not found!
```

Now I removed all downloaded files etc. and did a clean restart, maybe it will work.

**Comment by twshimwell** [comment]
Yeh indeed the macaroons are for proprietary data and the token is for the public data. 

Hmmm it looks like it still hasnt worked. Perhaps try this one instead:

export SINGULARITYENV_SDR_TOKEN=c49c6bb3-d074-a44d-4fca-1d3f7458055d

**Comment by mhardcastle** [comment]
Should we even be using the token for public data any more?

**Comment by twshimwell** [comment]
Hmmm yes ideally we wouldn't really. I think it doesn't work without it at present but I can ask SURF if there is a way it can be removed.

**Comment by AlexKurek** [comment]
This time I did exactly:

```
export SINGULARITYENV_SDR_TOKEN=c49c6bb3-d074-a44d-4fca-1d3f7458055d
export SINGULARITYENV_RCLONE_CONFIG_DIR=/storage/kurek/
export SINGULARITYENV_NUMEXPR_MAX_THREADS=28

time singularity exec -B /storage/kurek/ /home/kurek/ddf-pipeline/ddf-py3.singularity_opt.sif extraction.py --timeavg=1 --overwriteoutput --ncpu=28 4C29.30 > logBash.txt 2>&1
```

(new token) and got the same error.

**Comment by twshimwell** [comment]
In reprocessing_utils can you replace 'uv*.tar' with 'uv.tar'. Perhaps this is the issue. I don't really know why but sometimes the * seems to work but other times not. I should update to actually determine what the * is so that this problem doesn't happen.

**Comment by AlexKurek** [comment]
I did this:
https://github.com/mhardcastle/ddf-pipeline/commit/044bfaa2bcdcb0c0cbf9f86e2fc52f3078fabb4b
and it seems its working now!

```
[...]
Untarring files
[92mDoing field P130+32[0m
Initiating SDR download for field P130+32
Waiting for files to be online:
2/2... 
```

**Comment by twshimwell** [comment]
Oh good :) The issue now is for fields with multiple observations the data are uv_LXXXXX.tar where XXXXX is the observation ID for each observation. So we should fix this at some point too.

**Comment by mhardcastle** [comment]
That is already issue #283 , PR will be welcome (-:

Tim, as far as I can see we should not need the token to download public data (though it also won't hurt).
