### ISSUE TITLE
New software stack has wrong name for pybdsm/f components

### ISSUE THREAD

**Issue by mhardcastle** [mhardcastle/ddf-pipeline#298]
(upstream change but we can work round it in the pipeline by figuring out what file names are used)

```
======================================================= Cluster the sky model  =======================================================

Running: MakeCatalog.py --RestoredIm image_dirin_SSD_m.app.restored.fits --rmsmean_map [Noise.mean.fits,Noise.fits]
 - 17:54:19 - MakeCatalog                  | File image_dirin_SSD_m.app.restored.fits exist
--> Opened 'image_dirin_SSD_m.app.restored.fits'
Image size .............................. : (19845, 19845) pixels
Number of channels ...................... : 1
Number of Stokes parameters ............. : 1
Beam shape (major, minor, pos angle) .... : (3.33333e-03, 3.33333e-03, 90) degrees
Frequency of image ...................... : 144.627 MHz
Number of blank pixels .................. : 0 (0.0%)
Flux from sum of (non-blank) pixels ..... : 95.004 Jy
--> Calculating background rms and mean images
--> Skipping mean and rms image computation as external images supplied
-->    Opening mean image: Noise.mean.fits
--> Opened 'Noise.mean.fits'
-->    Opening rms image: Noise.fits
--> Opened 'Noise.fits'
--> Variation in rms image significant
--> Using 2D map for background rms
--> Variation in mean image not significant
--> Using constant background mean
Min/max values of background rms map .... : (5.84e-04, 2.42e-02) Jy/beam
Value of background mean ................ : -1e-05 Jy/beam
--> Expected 5-sigma-clipped false detection rate < fdr_ratio
--> Using sigma-clipping ('hard') thresholding
Minimum number of pixels per island ..... : 24
Number of islands found ................. : 962
Fitting islands with Gaussians .......... : [=================================================================================Total number of Gaussians fit to image .. : 1090
Total flux density in model ............. : 100.938 Jy
--> Grouping Gaussians into sources
Number of sources formed from Gaussians   : 1034
WARNING: All Gaussians were flagged for the following islands:
    Island #5 (x=1352, y=15131): fit with 1 Gaussian with flag = 256
    Island #117 (x=4840, y=9042): fit with 1 Gaussian with flag = 256
    Island #119 (x=4849, y=8981): fit with 1 Gaussian with flag = 256
    Island #168 (x=5697, y=10207): fit with 1 Gaussian with flag = 256
    Island #288 (x=7429, y=11896): fit with 1 Gaussian with flag = 256
    Island #326 (x=7939, y=14846): fit with 1 Gaussian with flag = 320
    Island #329 (x=7954, y=14890): fit with 1 Gaussian with flag = 256
    Island #403 (x=8841, y=671): fit with 1 Gaussian with flag = 256
    Island #440 (x=9217, y=13920): fit with 1 Gaussian with flag = 256
    Island #467 (x=9522, y=6430): fit with 1 Gaussian with flag = 256
    Island #507 (x=10095, y=9228): fit with 1 Gaussian with flag = 256
    Island #558 (x=10734, y=12517): fit with 1 Gaussian with flag = 256
    Island #582 (x=11034, y=1247): fit with 1 Gaussian with flag = 256
    Island #719 (x=12987, y=10717): fit with 1 Gaussian with flag = 256
    Island #854 (x=15203, y=15709): fit with 1 Gaussian with flag = 256
    Island #918 (x=16748, y=7696): fit with 1 Gaussian with flag = 256
    Island #929 (x=17060, y=10084): fit with 1 Gaussian with flag = 256
Please check these islands. If they are valid islands and
should be fit, try adjusting the flagging options (use
show_fit with "ch0_flagged=True" to see the flagged Gaussians
and "help 'flagging_opts'" to see the meaning of the flags)
or enabling the wavelet module (with "atrous_do=True").
To include empty islands in output source catalogs, set
incl_empty=True in the write_catalog task.

--> Wrote FITS file 'image_dirin_SSD_m.app.restored.pybdsf.srl.fits'
--> Wrote FITS file 'image_dirin_SSD_m.app.restored.pybdsf.gaul.fits'
--> Wrote BBS sky model 'image_dirin_SSD_m.app.restored.pybdsf.sky_in'
--> Wrote file 'image_dirin_SSD_m.app.restored.pybdsf_rms.fits'
--> Wrote file 'image_dirin_SSD_m.app.restored.pybdsf_mean.fits'
Running: ClusterCat.py --SourceCat image_dirin_SSD_m.app.restored.pybdsm.srl.fits --AvoidPolygons MaskDiffuse.pickle --DoPlot=0 --NGen 100 --NCPU 32 --OutClusterCat image_dirin_SSD_m.npy.ClusterCat.npy --NCluster 45
 - 17:57:17 - ClusterImage                 | Reading image_dirin_SSD_m.app.restored.pybdsm.srl.fits
Traceback (most recent call last):
  File "/usr/local/src/DDFacet/SkyModel/ClusterCat.py", line 342, in <module>
    main(options=options)
  File "/usr/local/src/DDFacet/SkyModel/ClusterCat.py", line 331, in main
    CIM=ClusterImage(**options.__dict__)
  File "/usr/local/src/DDFacet/SkyModel/ClusterCat.py", line 74, in __init__
    f=fits.open(self.SourceCat)
  File "/usr/lib/python3/dist-packages/astropy/io/fits/hdu/hdulist.py", line 164, in fitsopen
    return HDUList.fromfile(name, mode, memmap, save_backup, cache,
  File "/usr/lib/python3/dist-packages/astropy/io/fits/hdu/hdulist.py", line 401, in fromfile
    return cls._readfrom(fileobj=fileobj, mode=mode, memmap=memmap,
  File "/usr/lib/python3/dist-packages/astropy/io/fits/hdu/hdulist.py", line 1052, in _readfrom
    fileobj = _File(fileobj, mode=mode, memmap=memmap, cache=cache)
  File "/usr/lib/python3/dist-packages/astropy/utils/decorators.py", line 535, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/astropy/io/fits/file.py", line 175, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/usr/lib/python3/dist-packages/astropy/io/fits/file.py", line 564, in _open_filename
    self._file = fileobj_open(self.name, IO_FITS_MODES[mode])
  File "/usr/lib/python3/dist-packages/astropy/io/fits/util.py", line 392, in fileobj_open
    return open(filename, mode, buffering=0)
FileNotFoundError: [Errno 2] No such file or directory: 'image_dirin_SSD_m.app.restored.pybdsm.srl.fits'
 - 17:57:17 - ClearSHM                     | Clear shared memory
 - 17:57:17 - ClearSHM                     | Clear Semaphores
 - 17:57:17 - ClearSHM                     | Clear shared dictionaries
FAILED to run ClusterCat.py --SourceCat image_dirin_SSD_m.app.restored.pybdsm.srl.fits --AvoidPolygons MaskDiffuse.pickle --DoPlot=0 --NGen 100 --NCPU 32 --OutClusterCat image_dirin_SSD_m.npy.ClusterCat.npy --NCluster 45: return value is 1
Traceback (most recent call last):
  File "/usr/local/src/ddf-pipeline/scripts/pipeline.py", line 1948, in <module>
    main(o)
  File "/usr/local/src/ddf-pipeline/scripts/pipeline.py", line 1175, in main
    clusterGA(imagename="image_dirin_SSD_m.app.restored.fits",
  File "/usr/local/src/ddf-pipeline/scripts/pipeline.py", line 407, in clusterGA
    run(runcommand,dryrun=options['dryrun'],log=logfilename('MakeCluster-'+imagename+'.log',options=options),quiet=options['quiet'])
  File "/usr/local/src/ddf-pipeline/utils/auxcodes.py", line 68, in run
    die('FAILED to run '+s+': return value is '+str(retval),database=database)
  File "/usr/local/src/ddf-pipeline/utils/auxcodes.py", line 51, in die
    raise RuntimeError(s)
RuntimeError: FAILED to run ClusterCat.py --SourceCat image_dirin_SSD_m.app.restored.pybdsm.srl.fits --AvoidPolygons MaskDiffuse.pickle --DoPlot=0 --NGen 100 --NCPU 32 --OutClusterCat image_dirin_SSD_m.npy.ClusterCat.npy --NCluster 45: return value is 1
```

**Comment by mhardcastle** [comment]
Fixed in commit f0565f7a8c26176d2525101f890507405453bc04 .

Also now I know how to build Cyril's singularity image!
