### ISSUE TITLE
part (e) ddf-pipeline with new killMS/DDF versions

### ISSUE THREAD

**Issue by mhardcastle** [mhardcastle/ddf-pipeline#299]
killMS doesn't want to work with SM.Type=='Column'. (The new error message is mine.)

```
=============================================================== DI CAL ===============================================================

nch_step=16
Using (dt,df)=(12,20) for self-cal run of L841876_125MHz_uv_pre-cal.ms with (<|model|>,std)=(13.44,21.07) giving SNR=9.88
Running: kMS.py --MSName L841876_125MHz_uv_pre-cal.ms --SolverType KAFCA --PolMode Scalar --BaseImageName PredictDI_0 --dt 0.200000 --NIterKF 6 --CovQ 0.100000 --LambdaKF=0.500000 --NCPU 32 --OutSolsName DIS0 --InCol DATA --DebugPdb=0 --Weighting Natural --UVMinMax=0.100000,1000.000000 --SolsDir=SOLSDIR --SolverType CohJones --PolMode IFull --SkyModelCol DD_PREDICT --OutCol DATA_DI_CORRECTED --ApplyToDir 0 --dt 1.602324 --NChanSols 1
 - 11:49:19 - killMS                       | Checking system configuration:
 - 11:49:19 - killMS                       |   Max shared memory size is 102% of total RAM size
 - 11:49:19 - killMS                       | WARNING: sysctl vm.max_map_count = 65530. 
            This may be too little for large DDFacet and killMS jobs. If you get strange "file exists" 
            errors on /dev/shm, them try to bribe, beg or threaten your friendly local sysadmin into 
            setting vm.max_map_count=1000000 in /etc/sysctl.conf.
                
 - 11:49:19 - AsyncProcessPool             | Fixing parent process to vthread 0
 - 11:49:19 - AsyncProcessPool             | Worker affinities not specified, leaving unset
/usr/local/src/DDFacet/DDFacet/Data/ClassVisServer.py:607: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if DATA["sort_index"] is not None and DATA["Weights"] is not 1:
 - 11:49:21 - AsyncProcessPool             | Fixing parent process to vthread 0
 - 11:49:21 - AsyncProcessPool             | Worker affinities not specified, leaving unset
 - 11:49:21 - killMS                       | Predict Mode: using column DD_PREDICT
 - 11:49:26 - ClassVisServer               | Center of frequency domains [MHz]: [125.09613037109375]
 - 11:49:26 - ClassVisServer               | VisToSolsChanMapping [0, 0, 0, 0, 0, 0, 0, 0,  ...., 0, 0, 0, 0, 0, 0, 0, 0], (len = 20)
 - 11:49:26 - ClassVisServer               | SolsToVisChanMapping [(0, 20)], (len = 1)
/usr/local/src/killMS/killMS/Parset/DefaultParset.cfg
       __        _   __   __   ____    ____   ______     
      [  |  _   (_) [  | [  | |_   \  /   _|.' ____ \    
       | | / ]  __   | |  | |   |   \/   |  | (___ \_|   
       | '' <  [  |  | |  | |   | |\  /| |   _.____`.    
       | |`\ \  | |  | |  | |  _| |_\/_| |_ | \____) |   
      [__|  \_][___][___][___]|_____||_____| \______.'   
             This is version : 3.0.0.2
                                                        
 Selected Options:
* Data-related options
 - MSName ............................................ = L841876_125MHz_uv_pre-cal.ms
 - ConcatFreq ........................................ = False
 - TChunk ............................................ = 15
 - InCol ............................................. = DATA
 - OutCol ............................................ = DATA_DI_CORRECTED
 - FreePredictGainColName ............................ = None
 - FreePredictColName ................................ = None
 - Parallel .......................................... = 1

* Sky catalog related options
 - SkyModel .......................................... = ''
 - kills ............................................. = ''
 - invert ............................................ = False
 - Decorrelation ..................................... = ''
 - FreeFullSub ....................................... = 0
 - SkyModelCol ....................................... = DD_PREDICT
 - AppendCalSource ................................... = None

* Sky FITS Restored Cube
 - FITSSkyModel ...................................... = None
 - FITSNoiseBox ...................................... = 300
 - FITSTh ............................................ = 20

* Beam Options
 - BeamModel ......................................... = None
 - BeamAt ............................................ = facet
 - PhasedArrayMode ................................... = AE
 - DtBeamMin ......................................... = 5
 - CenterNorm ........................................ = True
 - NChanBeamPerMS .................................... = 1
 - FITSFile .......................................... = beam_$(corr)_$(reim).fits
 - FITSParAngleIncDeg ................................ = 5
 - FITSLAxis ......................................... = -X
 - FITSMAxis ......................................... = Y
 - FITSFeed .......................................... = ''
 - FITSVerbosity ..................................... = 1
 - FeedAngle ......................................... = 0
 - ApplyPJones ....................................... = 0
 - FlipVisibilityHands ............................... = 0
 - FITSFeedSwap ...................................... = 0
 - FITSFrame ......................................... = altaz

* Sky DDFacet image related options
 - BaseImageName ..................................... = PredictDI_0
 - DicoModel ......................................... = None
 - NodesFile ......................................... = None
 - ImagePredictParset ................................ = ''
 - OverS ............................................. = None
 - MaskImage ......................................... = None
 - wmax .............................................. = None
 - MaxFacetSize ...................................... = None
 - MinFacetSize ...................................... = None
 - RemoveDDFCache .................................... = False
 - DDFCacheDir ....................................... = ''
 - FilterNegComp ..................................... = False
 - NChanPredictPerMS ................................. = 0
 - ThSolve ........................................... = 0.0

* Data Selection
 - UVMinMax .......................................... = [0.1, 1000.0]
 - ChanSlice ......................................... = None
 - FlagAnts .......................................... = ''
 - DistMaxToCore ..................................... = 10000.0
 - FillFactor ........................................ = 1.0
 - FieldID ........................................... = 0
 - DDID .............................................. = 0

* Weighting scheme
 - Resolution ........................................ = 0.0
 - WeightInCol ....................................... = None
 - WeightFlagTh ...................................... = 0
 - Weighting ......................................... = Natural
 - Robust ............................................ = 0.0
 - WeightUVMinMax .................................... = None
 - WTUV .............................................. = 1

* Action options
 - DoPlot ............................................ = 0
 - SubOnly ........................................... = 0
 - NCPU .............................................. = 32
 - DoBar ............................................. = 1
 - NThread ........................................... = 1
 - DebugPdb .......................................... = 0
 - UpdateWeights ..................................... = 1

* PreApply killMS Solutions
 - PreApplySols ...................................... = ['']
 - PreApplyMode ...................................... = ['']

* Solution-related options
 - ExtSols ........................................... = ''
 - ClipMethod ........................................ = ['ResidAnt']
 - OutSolsName ....................................... = DIS0
 - ApplyToDir ........................................ = 0
 - MergeBeamToAppliedSol ............................. = 0
 - ApplyMode ......................................... = AP
 - SkipExistingSols .................................. = 0
 - SolsDir ........................................... = SOLSDIR

* Smoother solver
 - SmoothEnable ...................................... = False
 - SmoothInterpLevel ................................. = Inner
 - SmoothInterpMode .................................. = ['Amp:Unit', 'Phase:TEC+CPhase', 'Amp:MedianFilter_5_0_7', 'Amp:Clip_0.5_1.5', 'Phase:Zero']
 - AlsoSmoothATeam ................................... = 1

* Compression
 - CompressionMode ................................... = None
 - CompressionDirFile ................................ = None
 - MergeStations ..................................... = None

* Solver options
 - SolverType ........................................ = CohJones
 - AsyncPredict ...................................... = True
 - PrecisionDot ...................................... = D
 - PolMode ........................................... = IFull
 - dt ................................................ = 1.602324
 - NChanSols ......................................... = 1
 - Sequential ........................................ = 1

* CohJones additional options
 - NIterLM ........................................... = 7
 - LambdaLM .......................................... = 1
 - LambdaTk .......................................... = 0.0

 MS PROPERTIES: 
   - File Name: /beegfs/car/mjh/P182+85-new/L841876_125MHz_uv_pre-cal.ms
   - Column Name: DATA
   - Selection: FIELD_ID==0 && DATA_DESC_ID==0
   - Pointing center: (ra, dec)=(12:09:19.144, +84.48.35.449) 
   - Frequency = 125.10 MHz [ 124.17 -> 126.02 MHz]
   - Wavelength =  2.40 meters
   - Time bin =  8.0 seconds
   - Total Integration time =   8.00 hours
   - Number of antenna  = 59
   - Number of baseline = 1711
   - Number of SPW = 1
   - Number of channels = 20

 MS PROPERTIES: 
   - File Name: /beegfs/car/mjh/P182+85-new/L841876_125MHz_uv_pre-cal.ms
   - Column Name: DATA
   - Selection: FIELD_ID==0 && DATA_DESC_ID==0
   - Pointing center: (ra, dec)=(12:09:19.144, +84.48.35.449) 
   - Frequency = 125.10 MHz [ 124.17 -> 126.02 MHz]
   - Wavelength =  2.40 meters
   - Time bin =  8.0 seconds
   - Total Integration time =   8.00 hours
   - Number of antenna  = 59
   - Number of baseline = 1711
   - Number of SPW = 1
   - Number of channels = 20
 - 11:49:31 - ClassVisServer               | Center of frequency domains [MHz]: [125.09613037109375]
 - 11:49:31 - ClassVisServer               | VisToSolsChanMapping [0, 0, 0, 0, 0, 0, 0, 0,  ...., 0, 0, 0, 0, 0, 0, 0, 0], (len = 20)
 - 11:49:31 - ClassVisServer               | SolsToVisChanMapping [(0, 20)], (len = 1)
 - 11:49:33 - ClassWeighting               | Weighting in Natural mode
 - 11:49:34 - ClassVisServer               | Min weight is 1.000000 max is 1.000000
 - 11:49:36 - ClassWeighting               | Weighting in Natural mode
 - 11:49:37 - ClassVisServer               | Min weight is 1.000000 max is 1.000000

 MS PROPERTIES: 
   - File Name: /beegfs/car/mjh/P182+85-new/L841876_125MHz_uv_pre-cal.ms
   - Column Name: DD_PREDICT
   - Selection: FIELD_ID==0 && DATA_DESC_ID==0
   - Pointing center: (ra, dec)=(12:09:19.144, +84.48.35.449) 
   - Frequency = 125.10 MHz [ 124.17 -> 126.02 MHz]
   - Wavelength =  2.40 meters
   - Time bin =  8.0 seconds
   - Total Integration time =   8.00 hours
   - Number of antenna  = 59
   - Number of baseline = 1711
   - Number of SPW = 1
   - Number of channels = 20

 - 11:49:37 - AsyncProcessPool             | waiting for worker processes to start up
 - 11:49:38 - AsyncProcessPool             | Fixing parent process to vthread 0
 - 11:49:38 - AsyncProcessPool             | Worker affinities not specified, leaving unset
 - 11:49:38 - AsyncProcessPool             | waiting for worker processes to start up
 - 11:49:38 - ClassVisServer               | =================================================
 - 11:49:38 - ClassVisServer               | Load vis chunk #0: start
 - 11:49:38 - ClassVisServer               | Reading next data chunk in [ 0.00,  8.00] hours
 - 11:49:38 - ClassMS                      | [/beegfs/car/mjh/P182+85-new/L841876_125MHz_uv_pre-cal.ms] Reading rows [0 -> 6151045]
 - 11:49:42 - ClassMS                      |   data = DATA
 - 11:49:57 - ClassVisServer               | Channels are equidistant, can go fast
 - 11:50:05 - AsyncProcessPool             | process comp00: exception raised processing job loadNextChunk:Chunk=0: Traceback (most recent call last):
  File "/usr/local/src/DDFacet/DDFacet/Other/AsyncProcessPool.py", line 873, in _dispatch_job
    result = call(*args, **kwargs)
  File "/usr/local/src/killMS/killMS/Data/ClassVisServer.py", line 1197, in _workerLoadNextVisChunk
    raise RuntimeError("Incorrect option settings: SM.Type is %s, BeamAt is %s" % (self.SM.Type, self.GD["Beam"]["BeamAt"]))
RuntimeError: Incorrect option settings: SM.Type is Column, BeamAt is tessel

 - 11:50:05 - AsyncProcessPool             | loadNextChunk:Chunk=0: 1 jobs returned an error. Aborting.
Traceback (most recent call last):
  File "/usr/local/src/killMS/killMS/kMS.py", line 1558, in <module>
    main(OP=OP,MSName=MSName)
  File "/usr/local/src/killMS/killMS/kMS.py", line 929, in main
    Load=VS.LoadNextVisChunk()
  File "/usr/local/src/killMS/killMS/Data/ClassVisServer.py", line 733, in LoadNextVisChunk
    Message=APP.APP.awaitJobResults(NameJobThis)
  File "/usr/local/src/DDFacet/DDFacet/Other/AsyncProcessPool.py", line 764, in awaitJobResults
    raise RuntimeError("some distributed jobs have failed")
^CTraceback (most recent call last):
  File "/usr/local/src/ddf-pipeline/scripts/pipeline.py", line 1954, in <module>
    main(o)
  File "/usr/local/src/ddf-pipeline/scripts/pipeline.py", line 1220, in main
    killms_data('PredictDI_0',o['mslist'],'DIS0',colname=colname,
  File "/usr/local/src/ddf-pipeline/scripts/pipeline.py", line 536, in killms_data
    run(runcommand,dryrun=o['dryrun'],log=logfilename('KillMS-'+f_+'_'+rootfilename+'.log'),quiet=o['quiet'])
  File "/usr/local/src/ddf-pipeline/utils/auxcodes.py", line 65, in run
    retval=run_log(s,log,quiet)
  File "/usr/local/src/ddf-pipeline/utils/pipeline_logging.py", line 13, in run_log
    select.select([proc.stdout],[],[proc.stdout])
KeyboardInterrupt
```

**Comment by cyriltasse** [comment]
Ok this was really broken, took me the day to fix. I think it's working now... I'm compiling an image called `ddf_dev.sif` with the bug fixes...
