### ISSUE TITLE
error when subtracting outer region

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#301]
In new ddf.sif when trying to make use of the subtract outer region option in the pipeline I get during the image_full_wide_predict step (command is DDF.py --Misc-ConserveMemory=1 --Output-Name=image_full_wide_predict --Data-MS=big-mslist.txt --Deconv-PeakFactor 0.001000 --Data-ColName DATA --Parallel-NCPU=32 --Beam-CenterNorm=1 --Deconv-CycleFactor=0 --Deconv-MaxMinorIter=1000000 --Deconv-MaxMajorIter=3 --Deconv-Mode SSD --Beam-Model=LOFAR --Beam-PhasedArrayMode=A --Weight-Robust -0.200000 --Image-NPix=10000 --CF-wmax 50000 --CF-Nw 100 --Output-Also onNeds --Image-Cell 10.000000 --Facets-NFacets=11 --SSDClean-NEnlargeData 0 --Freq-NDegridBand 1 --Beam-NBand 1 --Facets-DiamMax 1.5 --Facets-DiamMin 0.1 --Deconv-RMSFactor=3.000000 --SSDClean-ConvFFTSwitch 10000 --Data-Sort 1 --Cache-Dir=. --Cache-DirWisdomFFTW=. --Debug-Pdb=never --Log-Memory 1 --GAClean-RMSFactorInitHMP 1.000000 --GAClean-MaxMinorIterInitHMP 10000.000000 --SSDClean-MaxIslandSize 100 --DDESolutions-SolsDir=SOLSDIR --Cache-Weight=reset --Misc-IgnoreDeprecationMarking=1 --Beam-At=facet --Output-Mode=Predict --Predict-ColName DATA_SUB --Predict-MaskSquare [0,1995] --Output-RestoringBeam 45.000000 --Weight-ColName="None" --Freq-NBand=2 --RIME-DecorrMode=FT --SSDClean-SSDSolvePars [S,Alpha] --SSDClean-BICFactor 0 --Mask-Auto=1 --Mask-SigTh=10.00 --Mask-External=image_full_wide.app.restored.fits.mask.fits --Predict-InitDicoModel=image_full_wide_im.DicoModel --GAClean-MinSizeInit=10)

   Init E-Jones ..................   1/48 [=                                                 ]  02%  - 0'08" 
    Init E-Jones ..................   2/48 [==                                                ]  04%  - 0'15" 
    Init E-Jones ..................   3/48 [===                                               ]  06%  - 0'20" 
    Init E-Jones ..................   4/48 [====                                              ]  08%  - 0'23" 
 - 11:32:29 - ClassImagerDeconv            [5.0/5.1 12.4/12.8 52.5Gb] model image @[123.14300537] MHz (min,max) = (-0.232617, 8.147083)
 - 11:32:29 - ClassImagerDeconv            [5.0/5.1 12.4/12.8 52.5Gb]   Zeroing model Inside square [2025 pixels]
 - 11:32:29 - DDFacet                      [5.0/5.1 12.4/12.8 52.5Gb] Traceback (most recent call last):
  File "/usr/local/src/DDFacet/DDFacet/DDF.py", line 457, in <module>
    main(OP, messages)
  File "/usr/local/src/DDFacet/DDFacet/DDF.py", line 289, in main
    Imager.GivePredict()
  File "/usr/local/src/DDFacet/DDFacet/Imager/ClassDeconvMachine.py", line 1033, in GivePredict
    nx,ny=self.FacetMachine.Npix
AttributeError: 'ClassFacetMachineTessel' object has no attribute 'Npix'

**Comment by twshimwell** [comment]
I think this one might be as:

self.FacetMachine now has Npix_x and Npix_y rather than only Npix (I think)
