### ISSUE TITLE
New versions part (f): Clipcal fails

### ISSUE THREAD

**Issue by mhardcastle** [mhardcastle/ddf-pipeline#302]
(after a restart from the problem in #299 )

```
 - 02:33:05 - killMS                       | Dataset(s) calibrated successfully in 00h35m15s
Running: ClipCal.py --MSName L841876_164MHz_uv_pre-cal.ms --ColName DATA_DI_CORRECTED
 - 02:33:12 - AsyncProcessPool             | Fixing parent process to vthread 0
 - 02:33:12 - AsyncProcessPool             | Worker affinities not specified, leaving unset
 - 02:33:12 - ClipCal                      | Reading visibility column DATA_DI_CORRECTED from L841876_164MHz_uv_pre-cal.ms
 - 02:33:20 - ClipCal                      |   Reading flags column: FLAG
 - 02:33:20 - ClipCal                      | [ch,pol, fracFlagged] = 0, 0, 0.125657
 - 02:33:20 - ClipCal                      | [ch,pol, fracFlagged] = 0, 1, 0.125657
 - 02:33:20 - ClipCal                      | [ch,pol, fracFlagged] = 0, 2, 0.125657
 - 02:33:21 - ClipCal                      | [ch,pol, fracFlagged] = 0, 3, 0.125657
 - 02:33:21 - ClipCal                      | [ch,pol, fracFlagged] = 1, 0, 0.113429
 - 02:33:21 - ClipCal                      | [ch,pol, fracFlagged] = 1, 1, 0.113429
 - 02:33:21 - ClipCal                      | [ch,pol, fracFlagged] = 1, 2, 0.113429
 - 02:33:21 - ClipCal                      | [ch,pol, fracFlagged] = 1, 3, 0.113429
 - 02:33:21 - ClipCal                      | [ch,pol, fracFlagged] = 2, 0, 0.111290
 - 02:33:21 - ClipCal                      | [ch,pol, fracFlagged] = 2, 1, 0.111290
 - 02:33:21 - ClipCal                      | [ch,pol, fracFlagged] = 2, 2, 0.111290
 - 02:33:21 - ClipCal                      | [ch,pol, fracFlagged] = 2, 3, 0.111290
 - 02:33:21 - ClipCal                      | [ch,pol, fracFlagged] = 3, 0, 0.117765
 - 02:33:21 - ClipCal                      | [ch,pol, fracFlagged] = 3, 1, 0.117765
 - 02:33:21 - ClipCal                      | [ch,pol, fracFlagged] = 3, 2, 0.117765
 - 02:33:21 - ClipCal                      | [ch,pol, fracFlagged] = 3, 3, 0.117765
 - 02:33:21 - ClipCal                      | [ch,pol, fracFlagged] = 4, 0, 0.101347
 - 02:33:21 - ClipCal                      | [ch,pol, fracFlagged] = 4, 1, 0.101347
 - 02:33:21 - ClipCal                      | [ch,pol, fracFlagged] = 4, 2, 0.101347
 - 02:33:21 - ClipCal                      | [ch,pol, fracFlagged] = 4, 3, 0.101347
 - 02:33:21 - ClipCal                      | [ch,pol, fracFlagged] = 5, 0, 0.099450
 - 02:33:21 - ClipCal                      | [ch,pol, fracFlagged] = 5, 1, 0.099450
 - 02:33:21 - ClipCal                      | [ch,pol, fracFlagged] = 5, 2, 0.099450
 - 02:33:21 - ClipCal                      | [ch,pol, fracFlagged] = 5, 3, 0.099450
 - 02:33:21 - ClipCal                      | [ch,pol, fracFlagged] = 6, 0, 0.097253
 - 02:33:21 - ClipCal                      | [ch,pol, fracFlagged] = 6, 1, 0.097253
 - 02:33:21 - ClipCal                      | [ch,pol, fracFlagged] = 6, 2, 0.097253
 - 02:33:21 - ClipCal                      | [ch,pol, fracFlagged] = 6, 3, 0.097253
 - 02:33:21 - ClipCal                      | [ch,pol, fracFlagged] = 7, 0, 0.091813
 - 02:33:21 - ClipCal                      | [ch,pol, fracFlagged] = 7, 1, 0.091813
 - 02:33:21 - ClipCal                      | [ch,pol, fracFlagged] = 7, 2, 0.091813
 - 02:33:22 - ClipCal                      | [ch,pol, fracFlagged] = 7, 3, 0.091813
 - 02:33:22 - ClipCal                      | [ch,pol, fracFlagged] = 8, 0, 0.088519
 - 02:33:22 - ClipCal                      | [ch,pol, fracFlagged] = 8, 1, 0.088519
 - 02:33:22 - ClipCal                      | [ch,pol, fracFlagged] = 8, 2, 0.088519
 - 02:33:22 - ClipCal                      | [ch,pol, fracFlagged] = 8, 3, 0.088519
 - 02:33:22 - ClipCal                      | [ch,pol, fracFlagged] = 9, 0, 0.085881
 - 02:33:22 - ClipCal                      | [ch,pol, fracFlagged] = 9, 1, 0.085881
 - 02:33:22 - ClipCal                      | [ch,pol, fracFlagged] = 9, 2, 0.085881
 - 02:33:22 - ClipCal                      | [ch,pol, fracFlagged] = 9, 3, 0.085881
 - 02:33:22 - ClipCal                      | [ch,pol, fracFlagged] = 10, 0, 1.000000
 - 02:33:22 - ClipCal                      | [ch,pol, fracFlagged] = 10, 1, 1.000000
 - 02:33:22 - ClipCal                      | [ch,pol, fracFlagged] = 10, 2, 1.000000
 - 02:33:22 - ClipCal                      | [ch,pol, fracFlagged] = 10, 3, 1.000000
 - 02:33:22 - ClipCal                      | [ch,pol, fracFlagged] = 11, 0, 1.000000
 - 02:33:22 - ClipCal                      | [ch,pol, fracFlagged] = 11, 1, 1.000000
 - 02:33:22 - ClipCal                      | [ch,pol, fracFlagged] = 11, 2, 1.000000
 - 02:33:22 - ClipCal                      | [ch,pol, fracFlagged] = 11, 3, 1.000000
 - 02:33:22 - ClipCal                      | [ch,pol, fracFlagged] = 12, 0, 0.096758
 - 02:33:22 - ClipCal                      | [ch,pol, fracFlagged] = 12, 1, 0.096758
 - 02:33:22 - ClipCal                      | [ch,pol, fracFlagged] = 12, 2, 0.096758
 - 02:33:22 - ClipCal                      | [ch,pol, fracFlagged] = 12, 3, 0.096758
 - 02:33:22 - ClipCal                      | [ch,pol, fracFlagged] = 13, 0, 0.073740
 - 02:33:22 - ClipCal                      | [ch,pol, fracFlagged] = 13, 1, 0.073740
 - 02:33:22 - ClipCal                      | [ch,pol, fracFlagged] = 13, 2, 0.073740
 - 02:33:22 - ClipCal                      | [ch,pol, fracFlagged] = 13, 3, 0.073740
 - 02:33:22 - ClipCal                      | [ch,pol, fracFlagged] = 14, 0, 0.071442
 - 02:33:22 - ClipCal                      | [ch,pol, fracFlagged] = 14, 1, 0.071442
 - 02:33:23 - ClipCal                      | [ch,pol, fracFlagged] = 14, 2, 0.071442
 - 02:33:23 - ClipCal                      | [ch,pol, fracFlagged] = 14, 3, 0.071442
 - 02:33:23 - ClipCal                      | [ch,pol, fracFlagged] = 15, 0, 0.075445
 - 02:33:23 - ClipCal                      | [ch,pol, fracFlagged] = 15, 1, 0.075445
 - 02:33:23 - ClipCal                      | [ch,pol, fracFlagged] = 15, 2, 0.075445
 - 02:33:23 - ClipCal                      | [ch,pol, fracFlagged] = 15, 3, 0.075445
 - 02:33:23 - ClipCal                      | [ch,pol, fracFlagged] = 16, 0, 0.125115
 - 02:33:23 - ClipCal                      | [ch,pol, fracFlagged] = 16, 1, 0.125115
 - 02:33:23 - ClipCal                      | [ch,pol, fracFlagged] = 16, 2, 0.125115
 - 02:33:23 - ClipCal                      | [ch,pol, fracFlagged] = 16, 3, 0.125115
 - 02:33:23 - ClipCal                      | [ch,pol, fracFlagged] = 17, 0, 0.130325
 - 02:33:23 - ClipCal                      | [ch,pol, fracFlagged] = 17, 1, 0.130325
 - 02:33:23 - ClipCal                      | [ch,pol, fracFlagged] = 17, 2, 0.130325
 - 02:33:23 - ClipCal                      | [ch,pol, fracFlagged] = 17, 3, 0.130325
 - 02:33:23 - ClipCal                      | [ch,pol, fracFlagged] = 18, 0, 0.171707
 - 02:33:23 - ClipCal                      | [ch,pol, fracFlagged] = 18, 1, 0.171707
 - 02:33:23 - ClipCal                      | [ch,pol, fracFlagged] = 18, 2, 0.171707
 - 02:33:23 - ClipCal                      | [ch,pol, fracFlagged] = 18, 3, 0.171707
 - 02:33:23 - ClipCal                      | [ch,pol, fracFlagged] = 19, 0, 0.183578
 - 02:33:23 - ClipCal                      | [ch,pol, fracFlagged] = 19, 1, 0.183578
 - 02:33:23 - ClipCal                      | [ch,pol, fracFlagged] = 19, 2, 0.183578
 - 02:33:23 - ClipCal                      | [ch,pol, fracFlagged] = 19, 3, 0.183578
 - 02:33:23 - ClipCal                      |   Zeroing flagged data
 - 02:33:24 - ClipCal                      |   Reading weights column IMAGING_WEIGHT
 - 02:33:25 - ClipCal                      | Fraction of zero-weighted visibilities previously non-flagged
 - 02:33:25 - ClipCal                      | Channel = 0
 - 02:33:27 - ClipCal                      | Channel = 1
 - 02:33:28 - ClipCal                      | Channel = 2
 - 02:33:30 - ClipCal                      | Channel = 3
 - 02:33:31 - ClipCal                      | Channel = 4
 - 02:33:33 - ClipCal                      | Channel = 5
 - 02:33:34 - ClipCal                      | Channel = 6
 - 02:33:36 - ClipCal                      | Channel = 7
 - 02:33:37 - ClipCal                      | Channel = 8
 - 02:33:39 - ClipCal                      | Channel = 9
 - 02:33:40 - ClipCal                      | Channel = 10
 - 02:33:41 - ClipCal                      |   All data is flagged - skipping...
 - 02:33:41 - ClipCal                      |   All data is flagged - skipping...
 - 02:33:41 - ClipCal                      |   All data is flagged - skipping...
 - 02:33:42 - ClipCal                      |   All data is flagged - skipping...
 - 02:33:42 - ClipCal                      | Channel = 11
 - 02:33:42 - ClipCal                      |   All data is flagged - skipping...
 - 02:33:42 - ClipCal                      |   All data is flagged - skipping...
 - 02:33:42 - ClipCal                      |   All data is flagged - skipping...
 - 02:33:43 - ClipCal                      |   All data is flagged - skipping...
 - 02:33:43 - ClipCal                      | Channel = 12
 - 02:33:44 - ClipCal                      | Channel = 13
 - 02:33:46 - ClipCal                      | Channel = 14
 - 02:33:47 - ClipCal                      | Channel = 15
 - 02:33:49 - ClipCal                      | Channel = 16
 - 02:33:50 - ClipCal                      | Channel = 17
 - 02:33:52 - ClipCal                      | Channel = 18
 - 02:33:53 - ClipCal                      | Channel = 19
 - 02:33:55 - ClipCal                      | Writing IMAGING_WEIGHT in L841876_164MHz_uv_pre-cal.ms
!!!!!!!!!!!!!!!
Traceback (most recent call last):
  File "/usr/local/src/ddf-pipeline/scripts/pipeline.py", line 1954, in <module>
    main(o)
  File "/usr/local/src/ddf-pipeline/scripts/pipeline.py", line 1288, in main
    CurrentDDkMSSolName=killms_data(CurrentBaseDicoModelName,o['mslist'],'DDS0',colname=colname,
  File "/usr/local/src/ddf-pipeline/scripts/pipeline.py", line 547, in killms_data
    outsols=smooth_solutions(mslist,outsols,catcher=None,dryrun=o['dryrun'],InterpToMSListFreqs=InterpToMSListFreqs,
  File "/usr/local/src/ddf-pipeline/scripts/pipeline.py", line 641, in smooth_solutions
    t0,t1 = get_solutions_timerange(solname)
  File "/usr/local/src/ddf-pipeline/scripts/pipeline.py", line 88, in get_solutions_timerange
    return np.min(t),np.max(t)
  File "<__array_function__ internals>", line 5, in amin
  File "/usr/local/lib/python3.9/dist-packages/numpy/core/fromnumeric.py", line 2830, in amin
    return _wrapreduction(a, np.minimum, 'min', axis, None, out,
  File "/usr/local/lib/python3.9/dist-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity
```

**Comment by cyriltasse** [comment]
This one is actually not `ClipCal.py` but the `BeamTimes` field being empty (issue opened alsewhere) and causing the crash in `get_solutions_timerange`. I have fixed it but I hit another issue right after in `SmoothSols`. Working on it :) So marking this one as closed
