### ISSUE TITLE
New version part (h): No crossmatches exist after group matching

### ISSUE THREAD

**Issue by cyriltasse** [mhardcastle/ddf-pipeline#306]
Hi -

I now get to the bootstrap code, and I get this

```
Total table length is 679
Filtered within 2.5 degrees: 415
Bright sources: 157
Remove close neighbours: 145
Table VLSS has 40 entries
Table WENSS has 0 entries
Traceback (most recent call last):
  File "/data/lofar/tasse/DEV/ddf-pipeline/scripts/bootstrap.py", line 273, in <module>
    run_bootstrap(o)
  File "/data/lofar/tasse/DEV/ddf-pipeline/scripts/bootstrap.py", line 167, in run_bootstrap
    make_catalogue('image_bootstrap_'+obsid+'.cube.int.restored.pybdsf.srl',ra,dec,2.5,cats,outnameprefix=obsid)
  File "/data/lofar/tasse/DEV/ddf-pipeline/utils/make_fitting_product.py", line 69, in make_catalogue
    raise RuntimeError('No crossmatches exist after group matching')
```

not sure how to solve this (this is @twshimwell galactic field) - @mhardcastle any idea?

**Comment by mhardcastle** [comment]
It's because there are no WENSS matches. I think you need to use NVSS instead.


________________________________
From: cyriltasse ***@***.***>
Sent: Tuesday, April 11, 2023 9:50:54 AM
To: mhardcastle/ddf-pipeline ***@***.***>
Cc: Martin Hardcastle ***@***.***>; Mention ***@***.***>
Subject: [mhardcastle/ddf-pipeline] New version part (h): No crossmatches exist after group matching (Issue #306)


Hi -

I now get to the bootstrap code, and I get this

Total table length is 679
Filtered within 2.5 degrees: 415
Bright sources: 157
Remove close neighbours: 145
Table VLSS has 40 entries
Table WENSS has 0 entries
Traceback (most recent call last):
  File "/data/lofar/tasse/DEV/ddf-pipeline/scripts/bootstrap.py", line 273, in <module>
    run_bootstrap(o)
  File "/data/lofar/tasse/DEV/ddf-pipeline/scripts/bootstrap.py", line 167, in run_bootstrap
    make_catalogue('image_bootstrap_'+obsid+'.cube.int.restored.pybdsf.srl',ra,dec,2.5,cats,outnameprefix=obsid)
  File "/data/lofar/tasse/DEV/ddf-pipeline/utils/make_fitting_product.py", line 69, in make_catalogue
    raise RuntimeError('No crossmatches exist after group matching')


not sure how to solve this (this is @twshimwell<https://github.com/twshimwell> galactic field) - @mhardcastle<https://github.com/mhardcastle> any idea?

**Comment by cyriltasse** [comment]
Thanks that solves it! :)
