### ISSUE TITLE
new version continued -- clipcal

### ISSUE THREAD

**Issue by mhardcastle** [mhardcastle/ddf-pipeline#307]
Resuming my tests:

```
Running: ClipCal.py --MSName L841876_164MHz_uv_pre-cal.ms --ColName DATA_DI_CORRECTED
 - 22:11:30 - AsyncProcessPool             | Fixing parent process to vthread 0
 - 22:11:30 - AsyncProcessPool             | Worker affinities not specified, leaving unset
 - 22:11:30 - ClipCal                      | Reading visibility column DATA_DI_CORRECTED from L841876_164MHz_uv_pre-cal.ms
 - 22:11:42 - ClipCal                      |   Reading flags column: FLAG
 - 22:11:42 - ClipCal                      | [ch,pol, fracFlagged] = 0, 0, 0.125657
 - 22:11:42 - ClipCal                      | [ch,pol, fracFlagged] = 0, 1, 0.125657
 - 22:11:42 - ClipCal                      | [ch,pol, fracFlagged] = 0, 2, 0.125657
 - 22:11:42 - ClipCal                      | [ch,pol, fracFlagged] = 0, 3, 0.125657
 - 22:11:42 - ClipCal                      | [ch,pol, fracFlagged] = 1, 0, 0.113429
 - 22:11:42 - ClipCal                      | [ch,pol, fracFlagged] = 1, 1, 0.113429
 - 22:11:42 - ClipCal                      | [ch,pol, fracFlagged] = 1, 2, 0.113429
 - 22:11:42 - ClipCal                      | [ch,pol, fracFlagged] = 1, 3, 0.113429
 - 22:11:42 - ClipCal                      | [ch,pol, fracFlagged] = 2, 0, 0.111290
 - 22:11:42 - ClipCal                      | [ch,pol, fracFlagged] = 2, 1, 0.111290
 - 22:11:42 - ClipCal                      | [ch,pol, fracFlagged] = 2, 2, 0.111290
 - 22:11:42 - ClipCal                      | [ch,pol, fracFlagged] = 2, 3, 0.111290
 - 22:11:42 - ClipCal                      | [ch,pol, fracFlagged] = 3, 0, 0.117765
 - 22:11:42 - ClipCal                      | [ch,pol, fracFlagged] = 3, 1, 0.117765
 - 22:11:43 - ClipCal                      | [ch,pol, fracFlagged] = 3, 2, 0.117765
 - 22:11:43 - ClipCal                      | [ch,pol, fracFlagged] = 3, 3, 0.117765
 - 22:11:43 - ClipCal                      | [ch,pol, fracFlagged] = 4, 0, 0.101347
 - 22:11:43 - ClipCal                      | [ch,pol, fracFlagged] = 4, 1, 0.101347
 - 22:11:43 - ClipCal                      | [ch,pol, fracFlagged] = 4, 2, 0.101347
 - 22:11:43 - ClipCal                      | [ch,pol, fracFlagged] = 4, 3, 0.101347
 - 22:11:43 - ClipCal                      | [ch,pol, fracFlagged] = 5, 0, 0.099450
 - 22:11:43 - ClipCal                      | [ch,pol, fracFlagged] = 5, 1, 0.099450
 - 22:11:43 - ClipCal                      | [ch,pol, fracFlagged] = 5, 2, 0.099450
 - 22:11:43 - ClipCal                      | [ch,pol, fracFlagged] = 5, 3, 0.099450
 - 22:11:43 - ClipCal                      | [ch,pol, fracFlagged] = 6, 0, 0.097253
 - 22:11:43 - ClipCal                      | [ch,pol, fracFlagged] = 6, 1, 0.097253
 - 22:11:43 - ClipCal                      | [ch,pol, fracFlagged] = 6, 2, 0.097253
 - 22:11:43 - ClipCal                      | [ch,pol, fracFlagged] = 6, 3, 0.097253
 - 22:11:43 - ClipCal                      | [ch,pol, fracFlagged] = 7, 0, 0.091813
 - 22:11:43 - ClipCal                      | [ch,pol, fracFlagged] = 7, 1, 0.091813
 - 22:11:43 - ClipCal                      | [ch,pol, fracFlagged] = 7, 2, 0.091813
 - 22:11:43 - ClipCal                      | [ch,pol, fracFlagged] = 7, 3, 0.091813
 - 22:11:43 - ClipCal                      | [ch,pol, fracFlagged] = 8, 0, 0.088519
 - 22:11:43 - ClipCal                      | [ch,pol, fracFlagged] = 8, 1, 0.088519
 - 22:11:43 - ClipCal                      | [ch,pol, fracFlagged] = 8, 2, 0.088519
 - 22:11:43 - ClipCal                      | [ch,pol, fracFlagged] = 8, 3, 0.088519
 - 22:11:43 - ClipCal                      | [ch,pol, fracFlagged] = 9, 0, 0.085881
 - 22:11:43 - ClipCal                      | [ch,pol, fracFlagged] = 9, 1, 0.085881
 - 22:11:43 - ClipCal                      | [ch,pol, fracFlagged] = 9, 2, 0.085881
 - 22:11:43 - ClipCal                      | [ch,pol, fracFlagged] = 9, 3, 0.085881
 - 22:11:43 - ClipCal                      | [ch,pol, fracFlagged] = 10, 0, 1.000000
 - 22:11:44 - ClipCal                      | [ch,pol, fracFlagged] = 10, 1, 1.000000
 - 22:11:44 - ClipCal                      | [ch,pol, fracFlagged] = 10, 2, 1.000000
 - 22:11:44 - ClipCal                      | [ch,pol, fracFlagged] = 10, 3, 1.000000
 - 22:11:44 - ClipCal                      | [ch,pol, fracFlagged] = 11, 0, 1.000000
 - 22:11:44 - ClipCal                      | [ch,pol, fracFlagged] = 11, 1, 1.000000
 - 22:11:44 - ClipCal                      | [ch,pol, fracFlagged] = 11, 2, 1.000000
 - 22:11:44 - ClipCal                      | [ch,pol, fracFlagged] = 11, 3, 1.000000
 - 22:11:44 - ClipCal                      | [ch,pol, fracFlagged] = 12, 0, 0.096758
 - 22:11:44 - ClipCal                      | [ch,pol, fracFlagged] = 12, 1, 0.096758
 - 22:11:44 - ClipCal                      | [ch,pol, fracFlagged] = 12, 2, 0.096758
 - 22:11:44 - ClipCal                      | [ch,pol, fracFlagged] = 12, 3, 0.096758
 - 22:11:44 - ClipCal                      | [ch,pol, fracFlagged] = 13, 0, 0.073740
 - 22:11:44 - ClipCal                      | [ch,pol, fracFlagged] = 13, 1, 0.073740
 - 22:11:44 - ClipCal                      | [ch,pol, fracFlagged] = 13, 2, 0.073740
 - 22:11:44 - ClipCal                      | [ch,pol, fracFlagged] = 13, 3, 0.073740
 - 22:11:44 - ClipCal                      | [ch,pol, fracFlagged] = 14, 0, 0.071442
 - 22:11:44 - ClipCal                      | [ch,pol, fracFlagged] = 14, 1, 0.071442
 - 22:11:44 - ClipCal                      | [ch,pol, fracFlagged] = 14, 2, 0.071442
 - 22:11:44 - ClipCal                      | [ch,pol, fracFlagged] = 14, 3, 0.071442
 - 22:11:44 - ClipCal                      | [ch,pol, fracFlagged] = 15, 0, 0.075445
 - 22:11:44 - ClipCal                      | [ch,pol, fracFlagged] = 15, 1, 0.075445
 - 22:11:44 - ClipCal                      | [ch,pol, fracFlagged] = 15, 2, 0.075445
 - 22:11:44 - ClipCal                      | [ch,pol, fracFlagged] = 15, 3, 0.075445
 - 22:11:44 - ClipCal                      | [ch,pol, fracFlagged] = 16, 0, 0.125115
 - 22:11:44 - ClipCal                      | [ch,pol, fracFlagged] = 16, 1, 0.125115
 - 22:11:44 - ClipCal                      | [ch,pol, fracFlagged] = 16, 2, 0.125115
 - 22:11:44 - ClipCal                      | [ch,pol, fracFlagged] = 16, 3, 0.125115
 - 22:11:44 - ClipCal                      | [ch,pol, fracFlagged] = 17, 0, 0.130325
 - 22:11:45 - ClipCal                      | [ch,pol, fracFlagged] = 17, 1, 0.130325
 - 22:11:45 - ClipCal                      | [ch,pol, fracFlagged] = 17, 2, 0.130325
 - 22:11:45 - ClipCal                      | [ch,pol, fracFlagged] = 17, 3, 0.130325
 - 22:11:45 - ClipCal                      | [ch,pol, fracFlagged] = 18, 0, 0.171707
 - 22:11:45 - ClipCal                      | [ch,pol, fracFlagged] = 18, 1, 0.171707
 - 22:11:45 - ClipCal                      | [ch,pol, fracFlagged] = 18, 2, 0.171707
 - 22:11:45 - ClipCal                      | [ch,pol, fracFlagged] = 18, 3, 0.171707
 - 22:11:45 - ClipCal                      | [ch,pol, fracFlagged] = 19, 0, 0.183578
 - 22:11:45 - ClipCal                      | [ch,pol, fracFlagged] = 19, 1, 0.183578
 - 22:11:45 - ClipCal                      | [ch,pol, fracFlagged] = 19, 2, 0.183578
 - 22:11:45 - ClipCal                      | [ch,pol, fracFlagged] = 19, 3, 0.183578
 - 22:11:45 - ClipCal                      |   Zeroing flagged data
 - 22:11:46 - ClipCal                      |   Reading weights column IMAGING_WEIGHT
 - 22:11:47 - ClipCal                      | Fraction of zero-weighted visibilities previously non-flagged
 - 22:11:47 - ClipCal                      | Channel = 0
 - 22:11:49 - ClipCal                      | Channel = 1
 - 22:11:50 - ClipCal                      | Channel = 2
 - 22:11:52 - ClipCal                      | Channel = 3
 - 22:11:53 - ClipCal                      | Channel = 4
 - 22:11:55 - ClipCal                      | Channel = 5
 - 22:11:56 - ClipCal                      | Channel = 6
 - 22:11:58 - ClipCal                      | Channel = 7
 - 22:11:59 - ClipCal                      | Channel = 8
 - 22:12:01 - ClipCal                      | Channel = 9
 - 22:12:02 - ClipCal                      | Channel = 10
 - 22:12:03 - ClipCal                      |   All data is flagged - skipping...
 - 22:12:03 - ClipCal                      |   All data is flagged - skipping...
 - 22:12:03 - ClipCal                      |   All data is flagged - skipping...
 - 22:12:03 - ClipCal                      |   All data is flagged - skipping...
 - 22:12:03 - ClipCal                      | Channel = 11
 - 22:12:04 - ClipCal                      |   All data is flagged - skipping...
 - 22:12:04 - ClipCal                      |   All data is flagged - skipping...
 - 22:12:04 - ClipCal                      |   All data is flagged - skipping...
 - 22:12:05 - ClipCal                      |   All data is flagged - skipping...
 - 22:12:05 - ClipCal                      | Channel = 12
 - 22:12:06 - ClipCal                      | Channel = 13
 - 22:12:08 - ClipCal                      | Channel = 14
 - 22:12:09 - ClipCal                      | Channel = 15
 - 22:12:11 - ClipCal                      | Channel = 16
 - 22:12:12 - ClipCal                      | Channel = 17
 - 22:12:14 - ClipCal                      | Channel = 18
 - 22:12:16 - ClipCal                      | Channel = 19
 - 22:12:17 - ClipCal                      | Writing IMAGING_WEIGHT in L841876_164MHz_uv_pre-cal.ms
!!!!!!!!!!!!!!!
Traceback (most recent call last):
  File "/usr/local/src/ddf-pipeline/scripts/pipeline.py", line 1954, in <module>
    main(o)
  File "/usr/local/src/ddf-pipeline/scripts/pipeline.py", line 1288, in main
    CurrentDDkMSSolName=killms_data(CurrentBaseDicoModelName,o['mslist'],'DDS0',colname=colname,
  File "/usr/local/src/ddf-pipeline/scripts/pipeline.py", line 547, in killms_data
    outsols=smooth_solutions(mslist,outsols,catcher=None,dryrun=o['dryrun'],InterpToMSListFreqs=InterpToMSListFreqs,
  File "/usr/local/src/ddf-pipeline/scripts/pipeline.py", line 641, in smooth_solutions
    t0,t1 = get_solutions_timerange(solname)
  File "/usr/local/src/ddf-pipeline/scripts/pipeline.py", line 88, in get_solutions_timerange
    return np.min(t),np.max(t)
  File "<__array_function__ internals>", line 5, in amin
  File "/usr/local/lib/python3.9/dist-packages/numpy/core/fromnumeric.py", line 2830, in amin
    return _wrapreduction(a, np.minimum, 'min', axis, None, out,
  File "/usr/local/lib/python3.9/dist-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
TypeError: cannot perform reduce with flexible type
```

**Comment by twshimwell** [comment]
hmm isn't this the same as #296 and #302. Are you using the ddf_dev.sif?

**Comment by cyriltasse** [comment]
Yeah this one I've fixed, I've pushed the changes to the repos, I'm updating the `ddf_dev.sif`, it should be finished compiling in 10 minutes or so

**Comment by cyriltasse** [comment]
ok the container is built

**Comment by mhardcastle** [comment]
Thanks Cyril. I'm travelling at the moment but will try this evening.


________________________________
