### ISSUE TITLE
fixsymlinks makes the extraction fail

### ISSUE THREAD

**Issue by botteon** [mhardcastle/ddf-pipeline#327]
Hi, I am extracting a target from a recently (<1 week) processed pointing but `sub-sources-outside-region.py` is crashing with the following error

```
....
DDS3_full
About to process 24 solution lines
Traceback (most recent call last):
  File "/opt/lofar/ddf-pipeline/scripts/sub-sources-outside-region.py", line 494, in <module>
    fixsymlinks(ddsols)
  File "/opt/lofar/ddf-pipeline/utils/fixsymlinks.py", line 24, in fixsymlinks
    filename = glob.glob(workdir+'/%s_%s*_%s.npz'%(ddsols,int(start_time),stype))[0]
IndexError: list index out of range
```

I understand that something has changed in the solution files, but I am not sure how to fix this...

**Comment by mhardcastle** [comment]
Fixed by #329, I assume?

**Comment by botteon** [comment]
No, it crashes at the prediction now, with this error

```
 - 14:01:12 - CacheManager                 [0.3/0.5 2.1/2.3 0.4Gb] cache directory ./L798420_121MHz_uv_pre-cal.ms.F0.D0.ddfcache/R0:6798145 does not exist, creating
DDFacet has encountered an unexpected error. Dropping you into pdb for a post-mortem.
(This is because you're running with --Debug-Pdb set to 'auto' and --Log-Boring is off.)
Traceback (most recent call last):
  File "/opt/lofar/DDFacet/bin/DDF.py", line 461, in <module>
    main(OP, messages)
  File "/opt/lofar/DDFacet/bin/DDF.py", line 287, in main
    Imager.Init()
  File "/opt/lofar/DDFacet/lib/python3.10/site-packages/DDFacet/Imager/ClassDeconvMachine.py", line 202, in Init
    self.VS = ClassVisServer.ClassVisServer(mslist,ColName=DC["Data"]["ColName"] if self.do_readcol else None,
  File "/opt/lofar/DDFacet/lib/python3.10/site-packages/DDFacet/Data/ClassVisServer.py", line 121, in __init__
    self.Init()
  File "/opt/lofar/DDFacet/lib/python3.10/site-packages/DDFacet/Data/ClassVisServer.py", line 160, in Init
    MS = ClassMS.ClassMS(
  File "/opt/lofar/DDFacet/lib/python3.10/site-packages/DDFacet/Data/ClassMS.py", line 134, in __init__
    self.ReadMSInfo(first_ms=first_ms,DoPrint=DoPrint)
  File "/opt/lofar/DDFacet/lib/python3.10/site-packages/DDFacet/Data/ClassMS.py", line 1212, in ReadMSInfo
    self.StrRA  = rad2hmsdms(self.rarad,Type="ra").replace(" ",":")
  File "/opt/lofar/DDFacet/lib/python3.10/site-packages/DDFacet/ToolsDir/rad2hmsdms.py", line 43, in rad2hmsdms
    degd=np.int(deg)
  File "/opt/lofar/pyenv-py3/lib64/python3.10/site-packages/numpy/__init__.py", line 299, in __getattr__
    warnings.warn(msg, DeprecationWarning, stacklevel=2)
DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

> /opt/lofar/pyenv-py3/lib64/python3.10/site-packages/numpy/__init__.py(299)__getattr__()
-> warnings.warn(msg, DeprecationWarning, stacklevel=2)

```

Do you have any idea what is going on?

**Comment by twshimwell** [comment]
I thought maybe you need to use python3.6 but maybe im wrong.

**Comment by twshimwell** [comment]
could it be something with the python version? im using 3.9

**Comment by mhardcastle** [comment]
numpy>1.19 and python>3.9 is not supported by DDFacet. So whichever singularity you're using, it's not enforcing the correct numpy version and Python versions. The error message above comes from python 3.10.

**Comment by botteon** [comment]
Oh ok, I close the issue then. Thanks

**Comment by tikk3r** [comment]
@botteon Does it crash because of the deprecation warning? In that case you should be able to work around it by adding `--Misc-IgnoreDeprecationMarking=1` to the DDF.py calls.

**Comment by botteon** [comment]
> @botteon Does it crash because of the deprecation warning? In that case you should be able to work around it by adding `--Misc-IgnoreDeprecationMarking=1` to the DDF.py calls.

Possibly, see the deprecation warning here https://github.com/mhardcastle/ddf-pipeline/issues/327#issuecomment-1644622784. Thanks for the suggestion
