### ISSUE TITLE
Numpy error

### ISSUE THREAD

**Issue by BiavaNadia** [mhardcastle/ddf-pipeline#349]
Hi,
I have just downloaded the ddf-pipeline from the master branch and built the singularity, but I got this numpy incompatibility error at the starting of the pipeline.
```
pipeline.py ~/software/ddf-pipeline/examples/tier1-jul2018-NVSS.cfg 
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem .
Traceback (most recent call last):
  File "/usr/local/src/ddf-pipeline/scripts/pipeline.py", line 34, in <module>
    from auxcodes import report,run,warn,die,Catcher,dotdict,separator,MSList
  File "/usr/local/src/ddf-pipeline/utils/auxcodes.py", line 15, in <module>
    from astropy.wcs import WCS
  File "/usr/local/lib/python3.9/dist-packages/astropy/wcs/__init__.py", line 27, in <module>
    from . import utils
  File "/usr/local/lib/python3.9/dist-packages/astropy/wcs/utils.py", line 9, in <module>
    from astropy.coordinates import (
  File "/usr/local/lib/python3.9/dist-packages/astropy/coordinates/__init__.py", line 12, in <module>
    from .builtin_frames import *
  File "/usr/local/lib/python3.9/dist-packages/astropy/coordinates/builtin_frames/__init__.py", line 28, in <module>
    from .altaz import AltAz
  File "/usr/local/lib/python3.9/dist-packages/astropy/coordinates/builtin_frames/altaz.py", line 82, in <module>
    class AltAz(BaseCoordinateFrame):
  File "/usr/lib/python3.9/abc.py", line 85, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/astropy/coordinates/baseframe.py", line 295, in __init_subclass__
    cls.get_frame_attr_defaults()
  File "/usr/local/lib/python3.9/dist-packages/astropy/coordinates/baseframe.py", line 733, in get_frame_attr_defaults
    return {name: getattr(cls, name) for name in cls.frame_attributes}
  File "/usr/local/lib/python3.9/dist-packages/astropy/coordinates/baseframe.py", line 733, in <dictcomp>
    return {name: getattr(cls, name) for name in cls.frame_attributes}
  File "/usr/local/lib/python3.9/dist-packages/astropy/coordinates/attributes.py", line 108, in __get__
    out, converted = self.convert_input(out)
  File "/usr/local/lib/python3.9/dist-packages/astropy/coordinates/attributes.py", line 178, in convert_input
    from astropy.time import Time
  File "/usr/local/lib/python3.9/dist-packages/astropy/time/__init__.py", line 47, in <module>
    from .formats import *
  File "/usr/local/lib/python3.9/dist-packages/astropy/time/formats.py", line 19, in <module>
    from . import _parse_times, conf, utils
ImportError: numpy.core.multiarray failed to import
```

**Comment by mhardcastle** [comment]
This must mean that a dependency has started to pull in a new version of numpy. Let me look at this.

**Comment by mhardcastle** [comment]
The singularity image will be upgraded to use a more up-to-date numpy (thus being easier to maintain) and newer public versions of DDF.py and kMS.py . Just need to get some of the bugs out of this setup before it can be released.

**Comment by mhardcastle** [comment]
The new singularity recipe is released and should fix this problem.
