### ISSUE TITLE
Pipeline Crashes at MakeCluster Step

### ISSUE THREAD

**Issue by tmartinezML** [mhardcastle/ddf-pipeline#362]
Hello,

I am trying to run the pipeline on a single MS obtained from a simulation. The pipeline crashes at the MakeCluster step, I attached the contents of the .log file.
The issue seems to begin where the RuntimeWarning (very top of the call stack) originates from, in GeneDist.py. My interpretation is that the cumulative distribution calculated therein (D) is all zero, i.e. maybe some empty data is passed at some point. I believe the subsequent errors are a consequence of that, caused by NaN values in the indices array.  I looked at the "restored" DDFacet image and it looks fine. Also the PyBDSF source list from the previous step is not empty, meaning sources are identified.. I am kind of lost here now, so I was hoping someone with more knowledge on the code might be able to spot any potential issues more easily.
I don't know if this could be related, but I am currently forced to pass the tgss catalog for masking, which might lead to weird behaviour since the sky I am working with is completely simulated and hence different from the tgss sky model at the same position. I have to pass it because otherwise, with the (default) tgss=None option, the pipeline can't run. The reason for that is in line 1015 of pipeline.py, where the value of tgss is required to be iterable, so passing None will give an error. Therefore, regardless of whether this is related to my actual problem, a fix for this would be awesome.
Many thanks in advance.

Running process with command: ClusterCat.py --SourceCat image_dirin_SSD_m.app.restored.pybdsm.srl.fits --DoPlot=0 --NGen 100 --NCPU 64 --OutClusterCat image_dirin_SSD_m.npy.ClusterCat.npy --NCluster 45
2024-10-21 16:53:24:  - 16:53:24 - ClusterImage                 | Reading image_dirin_SSD_m.app.restored.pybdsm.srl.fits
2024-10-21 16:53:24:  - 16:53:24 - ClusterImage                 | Warning: getting keyword NAXIS1 from comments
2024-10-21 16:53:24:  - 16:53:24 - ClusterImage                 | Warning: getting keyword CDELT1 from comments
2024-10-21 16:53:24:  - 16:53:24 - ClusterImage                 | Warning: getting keyword CRVAL1 from comments
2024-10-21 16:53:24:  - 16:53:24 - ClusterImage                 | Warning: getting keyword CRVAL2 from comments
2024-10-21 16:53:24:  - 16:53:24 - ClusterImage                 | Image center: 00:00:07.500 +23:23:42.904
2024-10-21 16:53:24:  - 16:53:24 - ClusterImage                 | Reading source catalog image_dirin_SSD_m.app.restored.pybdsm.srl.fits
2024-10-21 16:53:24:  - 16:53:24 - ClusterImage                 | Merging sources...
2024-10-21 16:53:24:  - 16:53:24 - ClusterImage                 | Have merged 105 -> 84
2024-10-21 16:53:24:  - 16:53:24 - ClusterImage                 |   Seleted 12 sources [out of 84] with flux density > 0.030000 Jy
2024-10-21 16:53:25:  - 16:53:25 - ClusterDEAP                  | Initialise population
2024-10-21 16:53:25: /usr/local/lib/python3.9/dist-packages/DDFacet/ToolsDir/GeneDist.py:93: RuntimeWarning: invalid value encountered in true_divide
2024-10-21 16:53:25:   D/=D[-1]
2024-10-21 16:53:25: Traceback (most recent call last):
2024-10-21 16:53:25:   File "/usr/local/bin/ClusterCat.py", line 8, in <module>
2024-10-21 16:53:25:     sys.exit(clustercat_main())
2024-10-21 16:53:25:   File "/usr/local/lib/python3.9/dist-packages/SkyModel/__main__.py", line 3, in clustercat_main
2024-10-21 16:53:25:     ClusterCat.driver()
2024-10-21 16:53:25:   File "/usr/local/lib/python3.9/dist-packages/SkyModel/ClusterCat.py", line 339, in driver
2024-10-21 16:53:25:     main(options=options)
2024-10-21 16:53:25:   File "/usr/local/lib/python3.9/dist-packages/SkyModel/ClusterCat.py", line 332, in main
2024-10-21 16:53:25:     CIM.Cluster()
2024-10-21 16:53:25:   File "/usr/local/lib/python3.9/dist-packages/SkyModel/ClusterCat.py", line 277, in Cluster
2024-10-21 16:53:25:     xyNodes,self.LPolygon=CC.Cluster()
2024-10-21 16:53:25:   File "/usr/local/lib/python3.9/dist-packages/SkyModel/Sky/ClassClusterDEAP.py", line 221, in Cluster
2024-10-21 16:53:25:     self.reinitPop2(pop)
2024-10-21 16:53:25:   File "/usr/local/lib/python3.9/dist-packages/SkyModel/Sky/ClassClusterDEAP.py", line 200, in reinitPop2
2024-10-21 16:53:25:     indSel=DDFacet.ToolsDir.GeneDist.GiveNonRedundantSample(self.S,self.nNode)
2024-10-21 16:53:25:   File "/usr/local/lib/python3.9/dist-packages/DDFacet/ToolsDir/GeneDist.py", line 58, in GiveNonRedundantSample
2024-10-21 16:53:25:     SSel=S[indices].copy()
2024-10-21 16:53:25: IndexError: arrays used as indices must be of integer (or boolean) type
Process terminated with return value 1

**Comment by twshimwell** [comment]
Hmmm I think it might be simply that there are not enough bright sources to define the 45 directions so that they each contain some amount of bright sources.

Does it work if you decrease the number of directions to say 10?

**Comment by tmartinezML** [comment]
@twshimwell Nailed it. I just tried with ndir = 10 and the error isn't appearing. Thank you so much!
Regarding the mask catalog, should I be concerned about it? Is there any workaround to avoid using it?

**Comment by mhardcastle** [comment]
You certainly shouldn't use a wrong mask. I think we should just handle a None here, and this is a bug in the pipeline, albeit it's not a mode that we have used in many years. Let me see if I can fix it on a short timescale.

**Comment by twshimwell** [comment]
I think if you added more sources into your simulated data it would also fix the issue (this step is kind of designed to work for about 60SB worth of data imaged over 8x8 square degrees)

**Comment by tmartinezML** [comment]
Hello,

Thanks for the fix, I really appreciate your fast and attentive support. Unfortunately, I am getting this now:

Traceback (most recent call last):
  File "/usr/local/src/ddf-pipeline/scripts/pipeline.py", line 1980, in <module>
    main(o)
  File "/usr/local/src/ddf-pipeline/scripts/pipeline.py", line 1015, in main
    if ((o['tgss'] is not None) and ('$$' in o['tgss'])) or ((o['catalogue'] is not None) and np.any(['$$' in l for l in o['catalogues']])):
KeyError: 'catalogue'

I'm pretty sure that's just a typo. Strangely, I tried adding a 'catalogue' option as a workaround and it didn't make a difference, but maybe there's a good reason for that.
While re-installing, I also saw that the bad file paths of #361 are still present in the singularity recipe, so I just wanted to let you know - sorry for mixing separate issues here :).
Thank you for your help.

**Comment by mhardcastle** [comment]
Sorry! I tried to fix another problem at the same time and of course it didn't work...

I've pushed what may be a fix to the whole issue that's created by having these entries unset at the start of the code, please take a look.

#361 is still open because just stripping those lines out breaks some functionality in our production build... I need to think of a workround. For me, the build doesn't fail if the files don't exist...

**Comment by tmartinezML** [comment]
Hello,

Thanks again for the fix, the None option works fine now. However, a different error arises at a later stage.
I attached the entire log file [DDF-image_dirin_SSD.log](https://github.com/user-attachments/files/17492633/DDF-image_dirin_SSD.log) so I don't omit any potentially useful information, but the key part is this:

`2024-10-23 15:22:35:  - 15:22:35 - DDFacet                      [0.2/0.4 0.9/1.1 0.7Gb] Traceback (most recent call last):
2024-10-23 15:22:35:   File "/usr/local/lib/python3.9/dist-packages/DDFacet/DDF.py", line 467, in driver
2024-10-23 15:22:35:     main(OP, messages)
2024-10-23 15:22:35:   File "/usr/local/lib/python3.9/dist-packages/DDFacet/DDF.py", line 293, in main
2024-10-23 15:22:35:     Imager.Init()
2024-10-23 15:22:35:   File "/usr/local/lib/python3.9/dist-packages/DDFacet/Imager/ClassDeconvMachine.py", line 261, in Init
2024-10-23 15:22:35:     self.MaskMachine=ClassMaskMachine.ClassMaskMachine(self.GD)
2024-10-23 15:22:35:   File "/usr/local/lib/python3.9/dist-packages/DDFacet/Imager/ClassMaskMachine.py", line 57, in __init__
2024-10-23 15:22:35:     self.readExternalMaskFromFits()
2024-10-23 15:22:35:   File "/usr/local/lib/python3.9/dist-packages/DDFacet/Imager/ClassMaskMachine.py", line 107, in readExternalMaskFromFits
2024-10-23 15:22:35:     raise RuntimeError("Provided external mask is empty! Will not continue.")`

It seems that when no external mask is provided, a blank mask is generated, and later DDFacet raises the error when it first reads it. I was able to work around the issue by setting my own fits mask as the external_fits_mask option, which might be better anyway. I am actually not sure whether this is a bug or intended behaviour?
Either way, it seems my original issues are now resolved, so again many thanks for your great support.
Cheers!

**Comment by mhardcastle** [comment]
Well, I guess we would ideally want the code to try to continue in this situation! But the best simulation of reality is probably to provide an external mask that contains some or all of your simulated sources, so that's probably a sensible approach for you at the moment.  Thanks for the feedback!
