### ISSUE TITLE
Size mismatch with External FITS Mask

### ISSUE THREAD

**Issue by tmartinezML** [mhardcastle/ddf-pipeline#363]
Hello,

I have been employing an external fits mask for my recent use of the pipeline on simulated data. For this, I used my initial simulated sky model to create a fits mask that has the same dimensions as the desired output image (i.e. "imsize" option in the ddf-pipeline), which in this example was 2400 pixels for 1 degree angular size. To my surprise, I got this error at the point in the pipeline where external mask is first used:

============================================================================================================================= External mask  =============================================================================================================================

Make blank external mask
Traceback (most recent call last):
  File "/usr/local/src/ddf-pipeline/scripts/pipeline.py", line 1989, in <module>
    main(o)
  File "/usr/local/src/ddf-pipeline/scripts/pipeline.py", line 1153, in main
    merge_mask(external_mask,o['external_fits_mask'],external_mask)
  File "/usr/local/src/ddf-pipeline/utils/make_extended_mask.py", line 30, in merge_mask
    hdu1[0].data = (map1 | map2).astype(np.float32)
ValueError: operands could not be broadcast together with shapes (1,1,2401,2401) (1,1,2400,2400)

So it seems that the pipeline requires a size of the fits mask that is different from the image output. In another example, for an image size of 12000 px (5 deg), the mask size was required to 12005 px, where interestingly the pixel difference is proportional to the size ratio of 5. I also noticed this seemingly related 'main field' entry in the (attached) [DDF-image_dirin_SSD_init.log](https://github.com/user-attachments/files/17544329/DDF-image_dirin_SSD_init.log):

2024-10-28 15:42:25:  - 15:42:25 - ClassFacetMachineTessel      [0.2/0.4 0.8/1.1 28.4Gb] Sizes (121 facets):
2024-10-28 15:42:25:  - 15:42:25 - ClassFacetMachineTessel      [0.2/0.4 0.8/1.1 28.4Gb]    - Main field :   [2401 x 2401] pix

I managed to work around the error by changing the resolution of the fits mask, so it would match the required pixel size while keeping the angular size unchanged. I'm not sure whether this is the best way to proceed, and also it would be great to know how to set the mask size beforehand, without having to first fail the pipeline and get the info from the error message.
Hence the question, what might be the reason for this size discrepancy and is it intended? If so, is there a way to know what size is required beforehand?
Many thanks in advance.

**Comment by mhardcastle** [comment]
As you say, this is a result of the fact that DDFacet makes its own choices about the image size (optimizing for the requirements of the FFTs it does). It picks the nearest suitable image size to the values provided by the user. Hence the ddf-pipeline imsize parameter only approximately gives the size of the output image.

We can use DDF's own code to work out what the true size will be in advance as follows:
```
[Singularity] mjh@lofar-server:~/git/DDFacet/DDFacet$ ipython3
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.20.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from DDFacet.ToolsDir.ModToolBox import EstimateNpix

In [2]: EstimateNpix?
Signature: EstimateNpix(Npix, Padding=1.0, min_size_fft=513)
Docstring:
Picks image size from the list of fast FFT sizes.
To avoid spectral leakage the number of taps in the FFT
must not be too small.
File:      /usr/local/src/DDFacet/DDFacet/ToolsDir/ModToolBox.py
Type:      function

In [3]: EstimateNpix(2400)
Out[3]: (2401, 2401)
```
but that's not hugely helpful from the perspective of ddf-pipeline since the user doesn't know this at the time of creating the parset. The correct thing to do would be to take any external FITS image and regrid it on to the DDF output at run time to make the merged mask. But this is an enhancement, and not a high-priority one...

**Comment by tmartinezML** [comment]
I see, thanks for clearing this up. I can certainly use this to estimate beforehand, so I think this gives me a way to solve the issue for now.

**Comment by IanHeywood** [comment]
In case it's useful to you, I made a pure python script in which I stole the relevant bits of the DDFacet code for this purpose, in case you want to run it in an enviroment that doesn't have a DDFacet installation.

https://gist.github.com/IanHeywood/18138e2f74759bd365ab8814291a12fe

**Comment by tmartinezML** [comment]
@IanHeywood Awesome, I actually had the same idea so it's great to have that confirmed. For my purpose, this certainly solves the issue. Thanks a lot!
