### ISSUE TITLE
Error in the pipeline, wrong log file name.

### ISSUE THREAD

**Issue by nudomarinero** [mhardcastle/ddf-pipeline#40]
The pipeline fails after a log file (```logs/DDF-image_bootstrap_/disk03/jsm/LOFAR.log```) is not found. I have checked and ```logs/DDF-image_bootstrap_``` does not exist.

According to the trace is like the variable ```imagename``` has a value like "DDF-image_bootstrap_/disk03/jsm/LOFAR" probably due to an error in the parsing of the names somewhere in the code (?). An example of the name for my typical input MS file is: ```/disk03/jsm/LOFAR_data/014_avg/L230779_SBgr000-10_uv.MS.pre-cal.ms```.

The full error is the following:
```
  File "/home/jsm/local/DDF/ddf-pipeline/scripts/bootstrap.py", line 201, in <module>
    run_bootstrap(o)
  File "/home/jsm/local/DDF/ddf-pipeline/scripts/bootstrap.py", line 88, in run_bootstrap
    ddf_image('image_bootstrap_'+obsid,'temp_mslist.txt',cleanmode='SSD',ddsols='killms_p1',applysols='P',majorcycles=4,robust=low_robust,uvrange=low_uvrange,beamsize=20,imsize=o['bsimsize']
,cellsize=o['bscell'],options=o,colname=o['colname'],automask=True,automask_threshold=15,smooth=True,cubemode=True)
  File "/home/jsm/local/DDF/ddf-pipeline/scripts/pipeline.py", line 212, in ddf_image
    run(runcommand,dryrun=options['dryrun'],log=logfilename('DDF-'+imagename+'.log',options=options),quiet=options['quiet'])
  File "/home/jsm/local/DDF/ddf-pipeline/utils/auxcodes.py", line 42, in run
    retval=run_log(s,log,quiet)
  File "/home/jsm/local/DDF/ddf-pipeline/utils/pipeline_logging.py", line 7, in run_log
    logfile = open(logfile, 'w')
IOError: [Errno 2] No such file or directory: 'logs/DDF-image_bootstrap_/disk03/jsm/LOFAR.log'
 - 22:29:52 - ClearSHM                  | Clear shared memory
 - 22:29:52 - ClearSHM                  | Clear Semaphores
 - 22:29:52 - ClearSHM                  | Clear shared dictionaries
Traceback (most recent call last):
  File "/home/jsm/local/DDF/ddf-pipeline/scripts/pipeline.py", line 508, in <module>
    run('bootstrap.py '+' '.join(sys.argv[1:]),log=None)
  File "/home/jsm/local/DDF/ddf-pipeline/utils/auxcodes.py", line 45, in run
    die('FAILED to run '+s+': return value is '+str(retval))
  File "/home/jsm/local/DDF/ddf-pipeline/utils/auxcodes.py", line 27, in die
    raise Exception(s)
Exception: FAILED to run bootstrap.py /home/jsm/repos/cuillin_processing/ddf_config/ddf014.cfg: return value is 1
```

**Comment by mhardcastle** [comment]
Thanks. I think I can see why this is but can you attach your mslist please?

**Comment by wllwen007** [comment]
You must have full paths in your mslists. Did you use make_mslist.py to make them?

**Comment by nudomarinero** [comment]
I see that the code in bootstrap.py assumes that the typical msname does not contains a directory path:
```
    # We use the individual ms in mslist.
    mslist=[s.strip() for s in open(o['mslist']).readlines()]
    
    obsids = [ms.split('_')[0] for ms in mslist]
    Uobsid = set(obsids)
```
this causes the extraction of the obsids to fail. This could be fixed spliting the path and basename or using a regular expression. But is this assumption made anywhere else in the code?

**Comment by wllwen007** [comment]
As far as I know it is only here that the obsids are extracted to do the bootstrap separately for multiple observations. Yes, I can fix this easily.

**Comment by nudomarinero** [comment]
I think this should fix it:
```
obsids = [os.path.basename(ms).split('_')[0] for ms in mslist]
```
Thanks!
