### ISSUE TITLE
crazy bootstrap issue

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#44]
Error message is below. I think we had this before and that time is was something hard wired. Maybe something similar again?

File image_bootstrap_L604564.app.restored.fits already exists, skipping DDF step
Source list exists, skipping source extraction
Total table length is 332
Filtered within 2.5 degrees: 132
Bright sources: 82
Remove close neighbours: 65
Table VLSS has 69 entries
Table NVSS has 987 entries
About to fit to 22 data points
Fitting 24 scale factors
Traceback (most recent call last):
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline/scripts/bootstrap.py", line 201, in <module>
    run_bootstrap(o)
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline/scripts/bootstrap.py", line 131, in run_bootstrap
    fitting_factors.run_all(1, name=obsid)
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline/utils/fitting_factors.py", line 109, in run_all
    args=(frequencies,fluxes,errors))
  File "build/bdist.linux-x86_64/egg/emcee/ensemble.py", line 102, in __init__
AssertionError: The number of walkers needs to be more than twice the dimension of your parameter space... unless you're crazy!
 - 14:33:22 - ClearSHM                  | Clear shared memory
 - 14:33:22 - ClearSHM                  | Clear Semaphores
 - 14:33:22 - ClearSHM                  | Clear shared dictionaries
FAILED to run bootstrap.py tier1.cfg: return value is 1
Traceback (most recent call last):
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline/scripts/pipeline.py", line 523, in <module>
    run('bootstrap.py '+' '.join(sys.argv[1:]),log=None)
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline/utils/auxcodes.py", line 45, in run
    die('FAILED to run '+s+': return value is '+str(retval))
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline/utils/auxcodes.py", line 27, in die
    raise Exception(s)
Exception: FAILED to run bootstrap.py tier1.cfg: return value is 1

**Comment by mhardcastle** [comment]
My mistake, the 'fix' I applied wasn't correct... I think it should be OK now.

**Comment by twshimwell** [comment]
in the master-fixes the nwalkers is now referenced before assignment. 

Should this bit

ndim=np.sum(smask)
nwalkers=2*(ndim+1)

go before the if statement?

**Comment by mhardcastle** [comment]
Sigh... yes, try again... trying to do too many things at once...

**Comment by twshimwell** [comment]
Thanks! Fixed. One off your list.
