### ISSUE TITLE
make pipeline dysco compatible

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#51]
Pipeline crashes quite early on with dysco compressed datasets.

[shimwell@lofar2 LOFARHBA_A665_P126_65]$ make_mslists.py
Traceback (most recent call last):
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline/scripts/make_mslists.py", line 53, in <module>
    make_list()
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline/scripts/make_mslists.py", line 23, in make_list
    ff=check_flagged(ms)
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline/scripts/make_mslists.py", line 10, in check_flagged
    t = pt.table(ms, readonly=True)
  File "/net/lofar1/data1/oonk/rh7_lof_feb2017_2_19_0/python-casacore/python-casacore/casacore/tables/table.py", line 315, in __init__
    Table.__init__(self, tabname, lockopt, opt)
RuntimeError: Table DataManager error: Data Manager class DyscoStMan is not registered

**Comment by twshimwell** [comment]
Solution -- source correct lofar software...
