### ISSUE TITLE
Bad astrometry  

### ISSUE THREAD

**Issue by cyriltasse** [mhardcastle/ddf-pipeline#72]
I see a bug after the `image_full_low` when doing the mask

```
MakeMask.py --RestoredIm=image_full_low.app.restored.fits --Th=3.0 --Box=50,2
 - 08:16:50 - AsyncProcessPool          | Fixing parent process to vthread 0
 - 08:16:50 - AsyncProcessPool          | Worker affinities not specified, leaving unset
2018-06-23 08:16:50	INFO	FITSCoordinateUtil::fromFITSHeader	celfix incurred the error Linear transformation matrix is singular
2018-06-23 08:16:50	INFO	FITSCoordinateUtil::fromFITSHeader	cylfix incurred the error Linear transformation matrix is singular
2018-06-23 08:16:50	WARN	FITSCoordinateUtil::fromFITSHeader	The wcs function failures are too severe to continue ...
2018-06-23 08:16:50	WARN	FITSImage::getImageAttributes (file /build/casacore-H661TW/casacore-2.4.1/images/Images/FITSImage.cc, line 720)	No proper coordinate system defined in FITS file. Using dummy linear system instead.
Traceback (most recent call last):
  File "/home/cyril.tasse/Wirtinger_Pack_nancep4/DDFacet/SkyModel/MakeMask.py", line 833, in <module>
    main(options=options)
  File "/home/cyril.tasse/Wirtinger_Pack_nancep4/DDFacet/SkyModel/MakeMask.py", line 825, in main
    options=options)
  File "/home/cyril.tasse/Wirtinger_Pack_nancep4/DDFacet/SkyModel/MakeMask.py", line 102, in __init__
    incr=np.abs(c.dict()["direction0"]["cdelt"][0])
KeyError: 'direction0'
```

Do you see it too? Opening the image in ipython, i get this dodgy header

```
In [7]: im.coordinates().dict()
Out[7]: 
{'linear0': {'_axes_sizes': array([6075, 6075,    1,    1], dtype=int32),
  '_image_axes': array([0, 1, 2, 3], dtype=int32),
  'axes': ['linear0', 'linear1', 'linear2', 'linear3'],
  'cdelt': array([1., 1., 1., 1.]),
  'crpix': array([3.038e+03, 3.038e+03, 1.000e+00, 1.000e+00]),
  'crval': array([0., 0., 0., 0.]),
  'pc': array([[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.],
         [0., 0., 0., 1.]]),
  'units': ['km', 'km', 'km', 'km']},
 'obsdate': {'m0': {'unit': 'd', 'value': 0.0},
  'refer': 'LAST',
  'type': 'epoch'},
 'observer': 'UNKNOWN',
 'pixelmap0': array([0, 1, 2, 3], dtype=int32),
 'pixelreplace0': array([0., 0., 0., 0.]),
 'pointingcenter': {'initial': True, 'value': array([0., 0.])},
 'telescope': 'UNKNOWN',
 'worldmap0': array([0, 1, 2, 3], dtype=int32),
 'worldreplace0': array([-3.038e+03, -3.038e+03, -1.000e+00, -1.000e+00])}
```

**Comment by mhardcastle** [comment]
I haven't seen that -- my latest run passed that point last night and didn't fail. Weird. Any bug would have to be in the FITS header writing code in DDFacet...

**Comment by cyriltasse** [comment]
Yeah - I'll investigate when I have time - weird...

**Comment by twshimwell** [comment]
was this one all fixed?

**Comment by mhardcastle** [comment]
Doesn't seem to have happened again. Let's close it.
