### ISSUE TITLE
fits file not found

### ISSUE THREAD

**Issue by amisk** [mhardcastle/ddf-pipeline#99]
Hi,

Im trying to run it on a small  subset of the lotss data, so it should work, but now I encountered:
```
Making the extended source mask
Running: MakeMask.py --RestoredIm=image_bootstrap.app.mean.fits --OutName=image_bootstrap.app.mean.fits.rmsmapmask --Th=3.0 --Box=50,2 --OutNameNoiseMap='image_bootstrap.app.mean.fits.rms'
 - 03:57:30 - MakeMask                  | Compute noise map...
 - 03:57:47 - ClassCasaImage            |   ----> Save data in casa image as FITS file image_bootstrap.app.mean.fits.rms.fits
 - 03:57:49 - ClassCasaImage            |   ----> Save data in casa image as FITS file image_bootstrap.app.mean.fits.rms.mean.fits
 - 03:57:51 - ClassCasaImage            |   ----> Save data in casa image as FITS file image_bootstrap.app.mean.fits.image_bootstrap.app.mean.fits.rmsmapmask.fits
Traceback (most recent call last):
  File "/home/amisk/programme/DDF/ddf-pipeline/scripts/pipeline.py", line 518, in <module>
    make_extended_mask(mask_base_image,'image_dirin_SSD.app.restored.fits',rmsthresh=o['extended_rms'],sizethresh=o['extended_size'],rootname='bootstrap',rmsfacet=o['rmsfacet'])
  File "/home/amisk/programme/DDF/ddf-pipeline/utils/make_extended_mask.py", line 43, in make_extended_mask
    get_rms_map2(infile,ds9region,prefix+'rms-low.fits')
  File "/home/amisk/programme/DDF/ddf-pipeline/utils/auxcodes.py", line 220, in get_rms_map2
    hdu=fits.open(infilename)
  File "/usr/local/lib/python2.7/dist-packages/astropy/io/fits/hdu/hdulist.py", line 166, in fitsopen
    lazy_load_hdus, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/astropy/io/fits/hdu/hdulist.py", line 404, in fromfile
    lazy_load_hdus=lazy_load_hdus, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/astropy/io/fits/hdu/hdulist.py", line 1015, in _readfrom
    fileobj = _File(fileobj, mode=mode, memmap=memmap, cache=cache)
  File "/usr/local/lib/python2.7/dist-packages/astropy/utils/decorators.py", line 493, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/astropy/io/fits/file.py", line 144, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/usr/local/lib/python2.7/dist-packages/astropy/io/fits/file.py", line 499, in _open_filename
    self._file = fileobj_open(self.name, IO_FITS_MODES[mode])
  File "/usr/local/lib/python2.7/dist-packages/astropy/io/fits/util.py", line 393, in fileobj_open
    return open(filename, mode)
IOError: [Errno 2] No such file or directory: 'image_bootstrap.app.mean.fits.rms.fits.fits'
```

Although the file "image_bootstrap.app.mean.fits.rms.fits" is present. Maybe the script appends a ".fits" at one point?

Can I just rename the file, or is the .fits.fits meant to be a different file?

**Comment by twshimwell** [comment]
Is this issue still relevant @amisk?

**Comment by amisk** [comment]
Never happened again, I guess it can be closed.

**Comment by botteon** [comment]
I have the same error using DR1 branch (field P23Hetdex20)

**Comment by twshimwell** [comment]
probably this line

infilename = '%s.rms.fits.fits'%infilename

in get_rms_map2

This line was to catch the makemask output which I think changed to not .fits.fits at some point so I guess this is some slight version difference with makemask and the pipeline.

**Comment by twshimwell** [comment]
For this issue im going to make a change to the DR1 ddf-pipeline replacing:

infilename = '%s.rms.fits.fits'%infilename

with 

infilename = '%s.rms.fits'%infilename

in get_rms_map2. I think this has happened because somehow the makemask and the ddf-pipeline for the DR1 release were slightly out of sync. Its a very minor change though so i think easiest just to make this change rather than try to match up the makemask and ddf-pipeline branches from 2years ago...

**Comment by twshimwell** [comment]
will close again but reopen if DR1 branch still has issues here.
